// Code generated by protoc-gen-protosource. DO NOT EDIT.

package testv1

import (
	"context"

	historyv1 "github.com/funinthecloud/protosource/history/v1"
	"github.com/funinthecloud/protosource/httpclient"
)

const routePath = "example/app/test/v1"

// HTTPClient is a typed HTTP client for the Test aggregate.
type HTTPClient struct {
	c httpclient.Doer
}

// NewHTTPClient creates a new Test HTTP client.
// Accepts httpclient.Doer for testability — use *httpclient.Client in
// production and a mock in tests.
func NewHTTPClient(c httpclient.Doer) *HTTPClient {
	return &HTTPClient{c: c}
}

// Create sends a Create command.
func (c *HTTPClient) Create(ctx context.Context, id string, body string) (*httpclient.ApplyResult, error) {
	cmd := &Create{
		Id:   id,
		Body: body,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Update sends a Update command.
func (c *HTTPClient) Update(ctx context.Context, id string, body string) (*httpclient.ApplyResult, error) {
	cmd := &Update{
		Id:   id,
		Body: body,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Lock sends a Lock command.
func (c *HTTPClient) Lock(ctx context.Context, id string) (*httpclient.ApplyResult, error) {
	cmd := &Lock{
		Id: id,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Unlock sends a Unlock command.
func (c *HTTPClient) Unlock(ctx context.Context, id string) (*httpclient.ApplyResult, error) {
	cmd := &Unlock{
		Id: id,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Load retrieves the current state of a Test aggregate.
func (c *HTTPClient) Load(ctx context.Context, id string) (*Test, error) {
	agg := &Test{}
	if err := c.c.Load(ctx, routePath, id, agg); err != nil {
		return nil, err
	}
	return agg, nil
}

// History retrieves the full event history for a Test aggregate.
func (c *HTTPClient) History(ctx context.Context, id string) (*historyv1.History, error) {
	return c.c.History(ctx, routePath, id)
}
