//go:build wireinject

// Code generated by protoc-gen-protosource. DO NOT EDIT.

package testv1

import (
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/memorystore"
	"github.com/google/wire"
)

func provideRepository(store *memorystore.MemoryStore, serializer *protobinaryserializer.Serializer) *protosource.Repository {
	return NewRepository(protosource.WithStore(store), protosource.WithSerializer(serializer))
}

// ProviderSet wires a Repository with a memorystore and protobinaryserializer.
// To use a different store or serializer, compose your own wire.NewSet with the
// appropriate package's ProviderSet (e.g., dynamodbstore.ProviderSet) and
// provideRepository.
var ProviderSet = wire.NewSet(
	memorystore.ProviderSet,
	protobinaryserializer.ProviderSet,
	provideRepository,
	wire.Bind(new(protosource.Repo), new(*protosource.Repository)),
)
