// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: example/app/test/v1/test_v1.proto

package testv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/funinthecloud/protosource/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_UNLOCKED    State = 1
	State_STATE_LOCKED      State = 2
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_UNLOCKED",
		2: "STATE_LOCKED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_UNLOCKED":    1,
		"STATE_LOCKED":      2,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_example_app_test_v1_test_v1_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_example_app_test_v1_test_v1_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{0}
}

// Test is the aggregate.
//
//	It must be defined first in the proto,
//	its name must match the first part of the package.
type Test struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version  int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	CreateAt int64                  `protobuf:"varint,3,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	CreateBy string                 `protobuf:"bytes,4,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	ModifyAt int64                  `protobuf:"varint,5,opt,name=modify_at,json=modifyAt,proto3" json:"modify_at,omitempty"`
	ModifyBy string                 `protobuf:"bytes,6,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	Body     string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	State    State                  `protobuf:"varint,8,opt,name=state,proto3,enum=example.app.test.v1.State" json:"state,omitempty"`
	// SET game fields for GSI testing
	Color         string `protobuf:"bytes,9,opt,name=color,proto3" json:"color,omitempty"`
	Shape         string `protobuf:"bytes,10,opt,name=shape,proto3" json:"shape,omitempty"`
	Number        string `protobuf:"bytes,11,opt,name=number,proto3" json:"number,omitempty"`
	Shading       string `protobuf:"bytes,12,opt,name=shading,proto3" json:"shading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Test) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Test) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Test) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *Test) GetModifyAt() int64 {
	if x != nil {
		return x.ModifyAt
	}
	return 0
}

func (x *Test) GetModifyBy() string {
	if x != nil {
		return x.ModifyBy
	}
	return ""
}

func (x *Test) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Test) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *Test) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Test) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Test) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Test) GetShading() string {
	if x != nil {
		return x.Shading
	}
	return ""
}

type TestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Test                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestList) Reset() {
	*x = TestList{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestList) ProtoMessage() {}

func (x *TestList) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestList.ProtoReflect.Descriptor instead.
func (*TestList) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{1}
}

func (x *TestList) GetItems() []*Test {
	if x != nil {
		return x.Items
	}
	return nil
}

// Create is the command that is used to create a test.
// Emits Created (domain fields) then Unlocked (initial state).
type Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Shape         string                 `protobuf:"bytes,5,opt,name=shape,proto3" json:"shape,omitempty"`
	Number        string                 `protobuf:"bytes,6,opt,name=number,proto3" json:"number,omitempty"`
	Shading       string                 `protobuf:"bytes,7,opt,name=shading,proto3" json:"shading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Create) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Create) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Create) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Create) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Create) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Create) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Create) GetShading() string {
	if x != nil {
		return x.Shading
	}
	return ""
}

// Update is the command that is used to update a test.
type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Shape         string                 `protobuf:"bytes,5,opt,name=shape,proto3" json:"shape,omitempty"`
	Number        string                 `protobuf:"bytes,6,opt,name=number,proto3" json:"number,omitempty"`
	Shading       string                 `protobuf:"bytes,7,opt,name=shading,proto3" json:"shading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{3}
}

func (x *Update) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Update) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Update) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Update) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Update) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Update) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Update) GetShading() string {
	if x != nil {
		return x.Shading
	}
	return ""
}

// Lock is the command that locks the aggregate.
type Lock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock) Reset() {
	*x = Lock{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{4}
}

func (x *Lock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lock) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

// Unlock is the command that unlocks the aggregate.
type Unlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unlock) Reset() {
	*x = Unlock{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unlock) ProtoMessage() {}

func (x *Unlock) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unlock.ProtoReflect.Descriptor instead.
func (*Unlock) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{5}
}

func (x *Unlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Unlock) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

// Created is the event emitted when we create a test.
type Created struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Shape         string                 `protobuf:"bytes,7,opt,name=shape,proto3" json:"shape,omitempty"`
	Number        string                 `protobuf:"bytes,8,opt,name=number,proto3" json:"number,omitempty"`
	Shading       string                 `protobuf:"bytes,9,opt,name=shading,proto3" json:"shading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Created) Reset() {
	*x = Created{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Created) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Created) ProtoMessage() {}

func (x *Created) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Created.ProtoReflect.Descriptor instead.
func (*Created) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{6}
}

func (x *Created) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Created) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Created) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Created) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Created) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Created) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Created) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Created) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Created) GetShading() string {
	if x != nil {
		return x.Shading
	}
	return ""
}

// Updated is the event emitted when we update a test.
type Updated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Shape         string                 `protobuf:"bytes,7,opt,name=shape,proto3" json:"shape,omitempty"`
	Number        string                 `protobuf:"bytes,8,opt,name=number,proto3" json:"number,omitempty"`
	Shading       string                 `protobuf:"bytes,9,opt,name=shading,proto3" json:"shading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Updated) Reset() {
	*x = Updated{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Updated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updated) ProtoMessage() {}

func (x *Updated) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updated.ProtoReflect.Descriptor instead.
func (*Updated) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{7}
}

func (x *Updated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Updated) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Updated) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Updated) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Updated) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Updated) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Updated) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Updated) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Updated) GetShading() string {
	if x != nil {
		return x.Shading
	}
	return ""
}

// Locked is the event emitted when the aggregate is locked.
type Locked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locked) Reset() {
	*x = Locked{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locked) ProtoMessage() {}

func (x *Locked) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locked.ProtoReflect.Descriptor instead.
func (*Locked) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{8}
}

func (x *Locked) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Locked) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Locked) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Locked) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

// Unlocked is the event emitted when the aggregate is unlocked.
type Unlocked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unlocked) Reset() {
	*x = Unlocked{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unlocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unlocked) ProtoMessage() {}

func (x *Unlocked) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unlocked.ProtoReflect.Descriptor instead.
func (*Unlocked) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{9}
}

func (x *Unlocked) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Unlocked) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Unlocked) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Unlocked) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

// Snapshot is the snapshot of the aggregate
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Snapshot      *Test                  `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_test_v1_test_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_example_app_test_v1_test_v1_proto_rawDescGZIP(), []int{10}
}

func (x *Snapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Snapshot) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Snapshot) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Snapshot) GetSnapshot() *Test {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_example_app_test_v1_test_v1_proto protoreflect.FileDescriptor

const file_example_app_test_v1_test_v1_proto_rawDesc = "" +
	"\n" +
	"!example/app/test/v1/test_v1.proto\x12\x13example.app.test.v1\x1a\x1bbuf/validate/validate.proto\x1a5funinthecloud/protosource/options/v1/options_v1.proto\"\xae\x03\n" +
	"\x04Test\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12%\n" +
	"\tcreate_at\x18\x03 \x01(\x03B\b¬\x1d\x04\n" +
	"\x02\b\n" +
	"R\bcreateAt\x12'\n" +
	"\tcreate_by\x18\x04 \x01(\tB\n" +
	"¬\x1d\x06\n" +
	"\x04\b\b\x10\x02R\bcreateBy\x12\x1b\n" +
	"\tmodify_at\x18\x05 \x01(\x03R\bmodifyAt\x12\x1b\n" +
	"\tmodify_by\x18\x06 \x01(\tR\bmodifyBy\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x12:\n" +
	"\x05state\x18\b \x01(\x0e2\x1a.example.app.test.v1.StateB\b¬\x1d\x04\n" +
	"\x02\b\tR\x05state\x12\"\n" +
	"\x05color\x18\t \x01(\tB\f¬\x1d\b\n" +
	"\x02\b\x03\n" +
	"\x02\b\x05R\x05color\x12$\n" +
	"\x05shape\x18\n" +
	" \x01(\tB\x0e¬\x1d\n" +
	"\n" +
	"\x02\b\x04\n" +
	"\x04\b\b\x10\x01R\x05shape\x12&\n" +
	"\x06number\x18\v \x01(\tB\x0e¬\x1d\n" +
	"\n" +
	"\x02\b\x06\n" +
	"\x04\b\a\x10\x01R\x06number\x12$\n" +
	"\ashading\x18\f \x01(\tB\n" +
	"¬\x1d\x06\n" +
	"\x04\b\a\x10\x02R\ashading:\n" +
	"ʬ\x1d\x06\x1a\x04\x10\x80\xa3\x05\";\n" +
	"\bTestList\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.example.app.test.v1.TestR\x05items\"\xd8\x01\n" +
	"\x06Create\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1d\n" +
	"\x05actor\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05actor\x12\x1b\n" +
	"\x04body\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04body\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x14\n" +
	"\x05shape\x18\x05 \x01(\tR\x05shape\x12\x16\n" +
	"\x06number\x18\x06 \x01(\tR\x06number\x12\x18\n" +
	"\ashading\x18\a \x01(\tR\ashading:\x1bʬ\x1d\x17\n" +
	"\x15\n" +
	"\aCreated\n" +
	"\bUnlocked\x10\x01\"\xc3\x01\n" +
	"\x06Update\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x14\n" +
	"\x05shape\x18\x05 \x01(\tR\x05shape\x12\x16\n" +
	"\x06number\x18\x06 \x01(\tR\x06number\x12\x18\n" +
	"\ashading\x18\a \x01(\tR\ashading:!ʬ\x1d\x1d\n" +
	"\x1b\n" +
	"\aUpdated\x10\x02\x1a\x0eSTATE_UNLOCKED\"N\n" +
	"\x04Lock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor: ʬ\x1d\x1c\n" +
	"\x1a\n" +
	"\x06Locked\x10\x02\x1a\x0eSTATE_UNLOCKED\"P\n" +
	"\x06Unlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor: ʬ\x1d\x1c\n" +
	"\x1a\n" +
	"\bUnlocked\x10\x02\x1a\fSTATE_LOCKED\"\xd3\x01\n" +
	"\aCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x14\n" +
	"\x05shape\x18\a \x01(\tR\x05shape\x12\x16\n" +
	"\x06number\x18\b \x01(\tR\x06number\x12\x18\n" +
	"\ashading\x18\t \x01(\tR\ashading:\x06ʬ\x1d\x02\x12\x00\"\xd3\x01\n" +
	"\aUpdated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x14\n" +
	"\x05shape\x18\a \x01(\tR\x05shape\x12\x16\n" +
	"\x06number\x18\b \x01(\tR\x06number\x12\x18\n" +
	"\ashading\x18\t \x01(\tR\ashading:\x06ʬ\x1d\x02\x12\x00\"n\n" +
	"\x06Locked\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor:\x14ʬ\x1d\x10\x12\x0e\x12\fSTATE_LOCKED\"r\n" +
	"\bUnlocked\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor:\x16ʬ\x1d\x12\x12\x10\x12\x0eSTATE_UNLOCKED\"\x9b\x01\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x125\n" +
	"\bsnapshot\x18\x05 \x01(\v2\x19.example.app.test.v1.TestR\bsnapshot:\bʬ\x1d\x04*\x02\b\x03*D\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATE_UNLOCKED\x10\x01\x12\x10\n" +
	"\fSTATE_LOCKED\x10\x02B\xdc\x01Ҭ\x1d\x02\b\x01\n" +
	"\x17com.example.app.test.v1B\vTestV1ProtoP\x01Z?github.com/funinthecloud/protosource/example/app/test/v1;testv1\xa2\x02\x03EAT\xaa\x02\x13Example.App.Test.V1\xca\x02\x13Example\\App\\Test\\V1\xe2\x02\x1fExample\\App\\Test\\V1\\GPBMetadata\xea\x02\x16Example::App::Test::V1b\x06proto3"

var (
	file_example_app_test_v1_test_v1_proto_rawDescOnce sync.Once
	file_example_app_test_v1_test_v1_proto_rawDescData []byte
)

func file_example_app_test_v1_test_v1_proto_rawDescGZIP() []byte {
	file_example_app_test_v1_test_v1_proto_rawDescOnce.Do(func() {
		file_example_app_test_v1_test_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_app_test_v1_test_v1_proto_rawDesc), len(file_example_app_test_v1_test_v1_proto_rawDesc)))
	})
	return file_example_app_test_v1_test_v1_proto_rawDescData
}

var file_example_app_test_v1_test_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_app_test_v1_test_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_example_app_test_v1_test_v1_proto_goTypes = []any{
	(State)(0),       // 0: example.app.test.v1.State
	(*Test)(nil),     // 1: example.app.test.v1.Test
	(*TestList)(nil), // 2: example.app.test.v1.TestList
	(*Create)(nil),   // 3: example.app.test.v1.Create
	(*Update)(nil),   // 4: example.app.test.v1.Update
	(*Lock)(nil),     // 5: example.app.test.v1.Lock
	(*Unlock)(nil),   // 6: example.app.test.v1.Unlock
	(*Created)(nil),  // 7: example.app.test.v1.Created
	(*Updated)(nil),  // 8: example.app.test.v1.Updated
	(*Locked)(nil),   // 9: example.app.test.v1.Locked
	(*Unlocked)(nil), // 10: example.app.test.v1.Unlocked
	(*Snapshot)(nil), // 11: example.app.test.v1.Snapshot
}
var file_example_app_test_v1_test_v1_proto_depIdxs = []int32{
	0, // 0: example.app.test.v1.Test.state:type_name -> example.app.test.v1.State
	1, // 1: example.app.test.v1.TestList.items:type_name -> example.app.test.v1.Test
	1, // 2: example.app.test.v1.Snapshot.snapshot:type_name -> example.app.test.v1.Test
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_example_app_test_v1_test_v1_proto_init() }
func file_example_app_test_v1_test_v1_proto_init() {
	if File_example_app_test_v1_test_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_app_test_v1_test_v1_proto_rawDesc), len(file_example_app_test_v1_test_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_app_test_v1_test_v1_proto_goTypes,
		DependencyIndexes: file_example_app_test_v1_test_v1_proto_depIdxs,
		EnumInfos:         file_example_app_test_v1_test_v1_proto_enumTypes,
		MessageInfos:      file_example_app_test_v1_test_v1_proto_msgTypes,
	}.Build()
	File_example_app_test_v1_test_v1_proto = out.File
	file_example_app_test_v1_test_v1_proto_goTypes = nil
	file_example_app_test_v1_test_v1_proto_depIdxs = nil
}
