//go:build wireinject

// Code generated by protoc-gen-protosource. DO NOT EDIT.

package samplev1dynamodb

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/funinthecloud/protosource"
	pkg "github.com/funinthecloud/protosource/example/app/samplenosnapshot/v1"
	opaquedynamo "github.com/funinthecloud/protosource/opaquedata/dynamo"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/dynamodbstore"
	"github.com/google/wire"
)

func provideOpaqueStore(client *dynamodb.Client, aggregatesTable string) *opaquedynamo.Store {
	return opaquedynamo.New(client, aggregatesTable)
}

func provideStore(client *dynamodb.Client, opaqueStore *opaquedynamo.Store, eventsTable string) (*dynamodbstore.DynamoDBStore, error) {
	return dynamodbstore.New(client,
		dynamodbstore.WithEventsTable(eventsTable),
		dynamodbstore.WithOpaqueStore(opaqueStore),
	)
}

func provideRepository(store *dynamodbstore.DynamoDBStore, serializer *protobinaryserializer.Serializer) *protosource.Repository {
	return pkg.NewRepository(store, serializer)
}

var ProviderSet = wire.NewSet(
	provideOpaqueStore,
	provideStore,
	dynamodbstore.ProviderSet,
	protobinaryserializer.ProviderSet,
	provideRepository,
)
