// Code generated by protoc-gen-protosource. DO NOT EDIT.






    
        
        
    

    

    

    

    

    

    

    

    

    

    

package testv1dynamodb

import (
    "github.com/funinthecloud/protosource"
    pkg "github.com/funinthecloud/protosource/example/app/test/v1"
    "github.com/goforj/wire"
)

// Repository wraps *protosource.Repository for the Test aggregate,
// giving Wire a distinct concrete type per aggregate.
type Repository struct{ *protosource.Repository }

// ProvideRepository creates a Test repository accepting interfaces.
func ProvideRepository(store protosource.Store, serializer protosource.Serializer) *Repository {
    return &Repository{pkg.NewRepository(store, serializer)}
}

// ProviderSet provides the Test repository and binds it to pkg.Repo.
var ProviderSet = wire.NewSet(
    ProvideRepository,
    wire.Bind(new(pkg.Repo), new(*Repository)),
)
