// Code generated by protoc-gen-protosource. DO NOT EDIT.

package testv1dynamodb

// EventsTableName is a named type for Wire to distinguish table name strings.
type EventsTableName string

// AggregatesTableName is a named type for Wire to distinguish table name strings.
type AggregatesTableName string
