// Code generated by protoc-gen-protosource. DO NOT EDIT.

package samplenoprefixv1

import (
	"fmt"
	"sync"

	"buf.build/go/protovalidate"
	"github.com/funinthecloud/protosource"
)

var (
	_validatorOnce sync.Once
	_validator     protovalidate.Validator
)

func validator() protovalidate.Validator {
	_validatorOnce.Do(func() {
		var err error
		_validator, err = protovalidate.New()
		if err != nil {
			panic(fmt.Sprintf("protovalidate.New: %v", err))
		}
	})
	return _validator
}

type Builder struct {
	id      string
	version int64
	Events  []protosource.Event
}

func NewBuilder(id string, version int64) *Builder {
	return &Builder{
		id:      id,
		version: version,
	}
}

func (b *Builder) nextVersion() int64 {
	b.version++
	return b.version
}

func (aggregate *Sample) setCreated(event protosource.Event) {
	aggregate.CreateAt = event.GetAt()
	aggregate.CreateBy = event.GetActor()
}
func (aggregate *Sample) setModified(event protosource.Event) {
	aggregate.ModifyAt = event.GetAt()
	aggregate.ModifyBy = event.GetActor()
}

// On applies an event to the aggregate, rebuilding its state.
// This method is called during Repository.Load to reconstruct from stored events,
// and during test scenarios. Events represent facts — never reject based on business rules.
func (aggregate *Sample) On(event protosource.Event) error {
	aggregate.Id = event.GetId()
	aggregate.Version = event.GetVersion()

	switch e := event.(type) {
	case *Created:
		aggregate.setCreated(e)
		aggregate.setModified(e)
		aggregate.Body = e.GetBody()
	case *Updated:
		aggregate.setModified(e)
		aggregate.Body = e.GetBody()
	default:
		return fmt.Errorf("%T: %w", e, protosource.ErrUnhandledEvent)
	}

	return nil
}

func (m *Create) CommandName() string {
	return "Create"
}

func (m *Create) ProtoValidate() error {
	if err := validator().Validate(m); err != nil {
		return fmt.Errorf("command %s: %w: %w", m.CommandName(), protosource.ErrValidationFailed, err)
	}
	return nil
}

func (m *Create) ValidateVersion(version int64) error {
	if version != 0 {
		return fmt.Errorf("command %s requires a new aggregate (version 0), got version %d: %w", m.CommandName(), version, protosource.ErrAlreadyCreated)
	}
	return nil
}
func (m *Create) EmitEvents(aggregate protosource.Aggregate) []protosource.Event {
	b := NewBuilder(m.GetId(), aggregate.GetVersion())
	b.Created(m.GetActor(), m.GetBody())
	if s, ok := aggregate.(protosource.Snapshoter); ok {
		if interval := s.SnapshotInterval(); interval > 0 && b.version%int64(interval) == 0 {
			b.Events = append(b.Events, s.Snapshot(b.version))
		}
	}
	return b.Events
}

func (m *Update) CommandName() string {
	return "Update"
}

func (m *Update) ProtoValidate() error {
	if err := validator().Validate(m); err != nil {
		return fmt.Errorf("command %s: %w: %w", m.CommandName(), protosource.ErrValidationFailed, err)
	}
	return nil
}

func (m *Update) ValidateVersion(version int64) error {
	if version == 0 {
		return fmt.Errorf("command %s requires an existing aggregate (version > 0), got version 0: %w", m.CommandName(), protosource.ErrNotCreatedYet)
	}
	return nil
}
func (m *Update) EmitEvents(aggregate protosource.Aggregate) []protosource.Event {
	b := NewBuilder(m.GetId(), aggregate.GetVersion())
	b.Updated(m.GetActor(), m.GetBody())
	if s, ok := aggregate.(protosource.Snapshoter); ok {
		if interval := s.SnapshotInterval(); interval > 0 && b.version%int64(interval) == 0 {
			b.Events = append(b.Events, s.Snapshot(b.version))
		}
	}
	return b.Events
}

func (m *Created) EventName() string {
	return "Created"
}

func (b *Builder) Created(Actor string, Body string) {
	event := &Created{
		Id:    b.id,
		Actor: Actor,
		Body:  Body,

		Version: b.nextVersion(),
		At:      protosource.NowMicros(),
	}
	b.Events = append(b.Events, event)
}

func (m *Updated) EventName() string {
	return "Updated"
}

func (b *Builder) Updated(Actor string, Body string) {
	event := &Updated{
		Id:    b.id,
		Actor: Actor,
		Body:  Body,

		Version: b.nextVersion(),
		At:      protosource.NowMicros(),
	}
	b.Events = append(b.Events, event)
}
