// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: funinthecloud/protosource/opaquedata/v1/opaquedata_v1.proto

package opaquedatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpaqueData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pk    string                 `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Sk    string                 `protobuf:"bytes,2,opt,name=sk,proto3" json:"sk,omitempty"`
	Ttl   int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Reserved for future optimistic locking. Always 0 for now.
	Version       int64  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Body          []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Gsi1Pk        string `protobuf:"bytes,6,opt,name=gsi1pk,proto3" json:"gsi1pk,omitempty"`
	Gsi1Sk        string `protobuf:"bytes,7,opt,name=gsi1sk,proto3" json:"gsi1sk,omitempty"`
	Gsi2Pk        string `protobuf:"bytes,8,opt,name=gsi2pk,proto3" json:"gsi2pk,omitempty"`
	Gsi2Sk        string `protobuf:"bytes,9,opt,name=gsi2sk,proto3" json:"gsi2sk,omitempty"`
	Gsi3Pk        string `protobuf:"bytes,10,opt,name=gsi3pk,proto3" json:"gsi3pk,omitempty"`
	Gsi3Sk        string `protobuf:"bytes,11,opt,name=gsi3sk,proto3" json:"gsi3sk,omitempty"`
	Gsi4Pk        string `protobuf:"bytes,12,opt,name=gsi4pk,proto3" json:"gsi4pk,omitempty"`
	Gsi4Sk        string `protobuf:"bytes,13,opt,name=gsi4sk,proto3" json:"gsi4sk,omitempty"`
	Gsi5Pk        string `protobuf:"bytes,14,opt,name=gsi5pk,proto3" json:"gsi5pk,omitempty"`
	Gsi5Sk        string `protobuf:"bytes,15,opt,name=gsi5sk,proto3" json:"gsi5sk,omitempty"`
	Gsi6Pk        string `protobuf:"bytes,16,opt,name=gsi6pk,proto3" json:"gsi6pk,omitempty"`
	Gsi6Sk        string `protobuf:"bytes,17,opt,name=gsi6sk,proto3" json:"gsi6sk,omitempty"`
	Gsi7Pk        string `protobuf:"bytes,18,opt,name=gsi7pk,proto3" json:"gsi7pk,omitempty"`
	Gsi7Sk        string `protobuf:"bytes,19,opt,name=gsi7sk,proto3" json:"gsi7sk,omitempty"`
	Gsi8Pk        string `protobuf:"bytes,20,opt,name=gsi8pk,proto3" json:"gsi8pk,omitempty"`
	Gsi8Sk        string `protobuf:"bytes,21,opt,name=gsi8sk,proto3" json:"gsi8sk,omitempty"`
	Gsi9Pk        string `protobuf:"bytes,22,opt,name=gsi9pk,proto3" json:"gsi9pk,omitempty"`
	Gsi9Sk        string `protobuf:"bytes,23,opt,name=gsi9sk,proto3" json:"gsi9sk,omitempty"`
	Gsi10Pk       string `protobuf:"bytes,24,opt,name=gsi10pk,proto3" json:"gsi10pk,omitempty"`
	Gsi10Sk       string `protobuf:"bytes,25,opt,name=gsi10sk,proto3" json:"gsi10sk,omitempty"`
	Gsi11Pk       string `protobuf:"bytes,26,opt,name=gsi11pk,proto3" json:"gsi11pk,omitempty"`
	Gsi11Sk       string `protobuf:"bytes,27,opt,name=gsi11sk,proto3" json:"gsi11sk,omitempty"`
	Gsi12Pk       string `protobuf:"bytes,28,opt,name=gsi12pk,proto3" json:"gsi12pk,omitempty"`
	Gsi12Sk       string `protobuf:"bytes,29,opt,name=gsi12sk,proto3" json:"gsi12sk,omitempty"`
	Gsi13Pk       string `protobuf:"bytes,30,opt,name=gsi13pk,proto3" json:"gsi13pk,omitempty"`
	Gsi13Sk       string `protobuf:"bytes,31,opt,name=gsi13sk,proto3" json:"gsi13sk,omitempty"`
	Gsi14Pk       string `protobuf:"bytes,32,opt,name=gsi14pk,proto3" json:"gsi14pk,omitempty"`
	Gsi14Sk       string `protobuf:"bytes,33,opt,name=gsi14sk,proto3" json:"gsi14sk,omitempty"`
	Gsi15Pk       string `protobuf:"bytes,34,opt,name=gsi15pk,proto3" json:"gsi15pk,omitempty"`
	Gsi15Sk       string `protobuf:"bytes,35,opt,name=gsi15sk,proto3" json:"gsi15sk,omitempty"`
	Gsi16Pk       string `protobuf:"bytes,36,opt,name=gsi16pk,proto3" json:"gsi16pk,omitempty"`
	Gsi16Sk       string `protobuf:"bytes,37,opt,name=gsi16sk,proto3" json:"gsi16sk,omitempty"`
	Gsi17Pk       string `protobuf:"bytes,38,opt,name=gsi17pk,proto3" json:"gsi17pk,omitempty"`
	Gsi17Sk       string `protobuf:"bytes,39,opt,name=gsi17sk,proto3" json:"gsi17sk,omitempty"`
	Gsi18Pk       string `protobuf:"bytes,40,opt,name=gsi18pk,proto3" json:"gsi18pk,omitempty"`
	Gsi18Sk       string `protobuf:"bytes,41,opt,name=gsi18sk,proto3" json:"gsi18sk,omitempty"`
	Gsi19Pk       string `protobuf:"bytes,42,opt,name=gsi19pk,proto3" json:"gsi19pk,omitempty"`
	Gsi19Sk       string `protobuf:"bytes,43,opt,name=gsi19sk,proto3" json:"gsi19sk,omitempty"`
	Gsi20Pk       string `protobuf:"bytes,44,opt,name=gsi20pk,proto3" json:"gsi20pk,omitempty"`
	Gsi20Sk       string `protobuf:"bytes,45,opt,name=gsi20sk,proto3" json:"gsi20sk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpaqueData) Reset() {
	*x = OpaqueData{}
	mi := &file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueData) ProtoMessage() {}

func (x *OpaqueData) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpaqueData.ProtoReflect.Descriptor instead.
func (*OpaqueData) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDescGZIP(), []int{0}
}

func (x *OpaqueData) GetPk() string {
	if x != nil {
		return x.Pk
	}
	return ""
}

func (x *OpaqueData) GetSk() string {
	if x != nil {
		return x.Sk
	}
	return ""
}

func (x *OpaqueData) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *OpaqueData) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OpaqueData) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OpaqueData) GetGsi1Pk() string {
	if x != nil {
		return x.Gsi1Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi1Sk() string {
	if x != nil {
		return x.Gsi1Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi2Pk() string {
	if x != nil {
		return x.Gsi2Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi2Sk() string {
	if x != nil {
		return x.Gsi2Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi3Pk() string {
	if x != nil {
		return x.Gsi3Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi3Sk() string {
	if x != nil {
		return x.Gsi3Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi4Pk() string {
	if x != nil {
		return x.Gsi4Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi4Sk() string {
	if x != nil {
		return x.Gsi4Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi5Pk() string {
	if x != nil {
		return x.Gsi5Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi5Sk() string {
	if x != nil {
		return x.Gsi5Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi6Pk() string {
	if x != nil {
		return x.Gsi6Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi6Sk() string {
	if x != nil {
		return x.Gsi6Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi7Pk() string {
	if x != nil {
		return x.Gsi7Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi7Sk() string {
	if x != nil {
		return x.Gsi7Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi8Pk() string {
	if x != nil {
		return x.Gsi8Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi8Sk() string {
	if x != nil {
		return x.Gsi8Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi9Pk() string {
	if x != nil {
		return x.Gsi9Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi9Sk() string {
	if x != nil {
		return x.Gsi9Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi10Pk() string {
	if x != nil {
		return x.Gsi10Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi10Sk() string {
	if x != nil {
		return x.Gsi10Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi11Pk() string {
	if x != nil {
		return x.Gsi11Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi11Sk() string {
	if x != nil {
		return x.Gsi11Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi12Pk() string {
	if x != nil {
		return x.Gsi12Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi12Sk() string {
	if x != nil {
		return x.Gsi12Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi13Pk() string {
	if x != nil {
		return x.Gsi13Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi13Sk() string {
	if x != nil {
		return x.Gsi13Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi14Pk() string {
	if x != nil {
		return x.Gsi14Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi14Sk() string {
	if x != nil {
		return x.Gsi14Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi15Pk() string {
	if x != nil {
		return x.Gsi15Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi15Sk() string {
	if x != nil {
		return x.Gsi15Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi16Pk() string {
	if x != nil {
		return x.Gsi16Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi16Sk() string {
	if x != nil {
		return x.Gsi16Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi17Pk() string {
	if x != nil {
		return x.Gsi17Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi17Sk() string {
	if x != nil {
		return x.Gsi17Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi18Pk() string {
	if x != nil {
		return x.Gsi18Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi18Sk() string {
	if x != nil {
		return x.Gsi18Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi19Pk() string {
	if x != nil {
		return x.Gsi19Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi19Sk() string {
	if x != nil {
		return x.Gsi19Sk
	}
	return ""
}

func (x *OpaqueData) GetGsi20Pk() string {
	if x != nil {
		return x.Gsi20Pk
	}
	return ""
}

func (x *OpaqueData) GetGsi20Sk() string {
	if x != nil {
		return x.Gsi20Sk
	}
	return ""
}

var File_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto protoreflect.FileDescriptor

const file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDesc = "" +
	"\n" +
	";funinthecloud/protosource/opaquedata/v1/opaquedata_v1.proto\x12'funinthecloud.protosource.opaquedata.v1\"\xd8\b\n" +
	"\n" +
	"OpaqueData\x12\x0e\n" +
	"\x02pk\x18\x01 \x01(\tR\x02pk\x12\x0e\n" +
	"\x02sk\x18\x02 \x01(\tR\x02sk\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x16\n" +
	"\x06gsi1pk\x18\x06 \x01(\tR\x06gsi1pk\x12\x16\n" +
	"\x06gsi1sk\x18\a \x01(\tR\x06gsi1sk\x12\x16\n" +
	"\x06gsi2pk\x18\b \x01(\tR\x06gsi2pk\x12\x16\n" +
	"\x06gsi2sk\x18\t \x01(\tR\x06gsi2sk\x12\x16\n" +
	"\x06gsi3pk\x18\n" +
	" \x01(\tR\x06gsi3pk\x12\x16\n" +
	"\x06gsi3sk\x18\v \x01(\tR\x06gsi3sk\x12\x16\n" +
	"\x06gsi4pk\x18\f \x01(\tR\x06gsi4pk\x12\x16\n" +
	"\x06gsi4sk\x18\r \x01(\tR\x06gsi4sk\x12\x16\n" +
	"\x06gsi5pk\x18\x0e \x01(\tR\x06gsi5pk\x12\x16\n" +
	"\x06gsi5sk\x18\x0f \x01(\tR\x06gsi5sk\x12\x16\n" +
	"\x06gsi6pk\x18\x10 \x01(\tR\x06gsi6pk\x12\x16\n" +
	"\x06gsi6sk\x18\x11 \x01(\tR\x06gsi6sk\x12\x16\n" +
	"\x06gsi7pk\x18\x12 \x01(\tR\x06gsi7pk\x12\x16\n" +
	"\x06gsi7sk\x18\x13 \x01(\tR\x06gsi7sk\x12\x16\n" +
	"\x06gsi8pk\x18\x14 \x01(\tR\x06gsi8pk\x12\x16\n" +
	"\x06gsi8sk\x18\x15 \x01(\tR\x06gsi8sk\x12\x16\n" +
	"\x06gsi9pk\x18\x16 \x01(\tR\x06gsi9pk\x12\x16\n" +
	"\x06gsi9sk\x18\x17 \x01(\tR\x06gsi9sk\x12\x18\n" +
	"\agsi10pk\x18\x18 \x01(\tR\agsi10pk\x12\x18\n" +
	"\agsi10sk\x18\x19 \x01(\tR\agsi10sk\x12\x18\n" +
	"\agsi11pk\x18\x1a \x01(\tR\agsi11pk\x12\x18\n" +
	"\agsi11sk\x18\x1b \x01(\tR\agsi11sk\x12\x18\n" +
	"\agsi12pk\x18\x1c \x01(\tR\agsi12pk\x12\x18\n" +
	"\agsi12sk\x18\x1d \x01(\tR\agsi12sk\x12\x18\n" +
	"\agsi13pk\x18\x1e \x01(\tR\agsi13pk\x12\x18\n" +
	"\agsi13sk\x18\x1f \x01(\tR\agsi13sk\x12\x18\n" +
	"\agsi14pk\x18  \x01(\tR\agsi14pk\x12\x18\n" +
	"\agsi14sk\x18! \x01(\tR\agsi14sk\x12\x18\n" +
	"\agsi15pk\x18\" \x01(\tR\agsi15pk\x12\x18\n" +
	"\agsi15sk\x18# \x01(\tR\agsi15sk\x12\x18\n" +
	"\agsi16pk\x18$ \x01(\tR\agsi16pk\x12\x18\n" +
	"\agsi16sk\x18% \x01(\tR\agsi16sk\x12\x18\n" +
	"\agsi17pk\x18& \x01(\tR\agsi17pk\x12\x18\n" +
	"\agsi17sk\x18' \x01(\tR\agsi17sk\x12\x18\n" +
	"\agsi18pk\x18( \x01(\tR\agsi18pk\x12\x18\n" +
	"\agsi18sk\x18) \x01(\tR\agsi18sk\x12\x18\n" +
	"\agsi19pk\x18* \x01(\tR\agsi19pk\x12\x18\n" +
	"\agsi19sk\x18+ \x01(\tR\agsi19sk\x12\x18\n" +
	"\agsi20pk\x18, \x01(\tR\agsi20pk\x12\x18\n" +
	"\agsi20sk\x18- \x01(\tR\agsi20skB\xc0\x02\n" +
	"+com.funinthecloud.protosource.opaquedata.v1B\x11OpaquedataV1ProtoP\x01Z?github.com/funinthecloud/protosource/opaquedata/v1;opaquedatav1\xa2\x02\x03FPO\xaa\x02'Funinthecloud.Protosource.Opaquedata.V1\xca\x02'Funinthecloud\\Protosource\\Opaquedata\\V1\xe2\x023Funinthecloud\\Protosource\\Opaquedata\\V1\\GPBMetadata\xea\x02*Funinthecloud::Protosource::Opaquedata::V1b\x06proto3"

var (
	file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDescOnce sync.Once
	file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDescData []byte
)

func file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDescGZIP() []byte {
	file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDescOnce.Do(func() {
		file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDesc), len(file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDesc)))
	})
	return file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDescData
}

var file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_goTypes = []any{
	(*OpaqueData)(nil), // 0: funinthecloud.protosource.opaquedata.v1.OpaqueData
}
var file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_init() }
func file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_init() {
	if File_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDesc), len(file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_goTypes,
		DependencyIndexes: file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_depIdxs,
		MessageInfos:      file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_msgTypes,
	}.Build()
	File_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto = out.File
	file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_goTypes = nil
	file_funinthecloud_protosource_opaquedata_v1_opaquedata_v1_proto_depIdxs = nil
}
