// Code generated by protoc-gen-protosource. DO NOT EDIT.

package samplev1

import (
	"context"
	"errors"
	"net/http"

	"github.com/funinthecloud/protosource"
	"google.golang.org/protobuf/encoding/protojson"
)

// Handlers provides request handler functions for the Sample aggregate.
type Handlers struct {
	repo protosource.Repo
}

// NewHandlers creates a new Handlers instance with the given repository.
func NewHandlers(repo protosource.Repo) *Handlers {
	return &Handlers{repo: repo}
}

// HandleCreate processes a Create command.
func (h *Handlers) HandleCreate(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &Create{}
	if err := protojson.Unmarshal([]byte(request.Body), cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       `{"id":"` + cmd.GetId() + `","version":` + itoa(version) + `}`,
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// HandleUpdate processes a Update command.
func (h *Handlers) HandleUpdate(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &Update{}
	if err := protojson.Unmarshal([]byte(request.Body), cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       `{"id":"` + cmd.GetId() + `","version":` + itoa(version) + `}`,
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// HandleGet retrieves the current state of a Sample aggregate.
func (h *Handlers) HandleGet(ctx context.Context, request protosource.Request) protosource.Response {
	id := extractID(request)
	if id == "" {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"missing required parameter: id"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	aggregate, err := h.repo.Load(ctx, id)
	if err != nil {
		if errors.Is(err, protosource.ErrAggregateNotFound) {
			return protosource.Response{
				StatusCode: http.StatusNotFound,
				Body:       `{"error":"aggregate not found"}`,
				Headers:    map[string]string{"Content-Type": "application/json"},
			}
		}
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"internal server error"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	body, err := protojson.Marshal(aggregate)
	if err != nil {
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"failed to serialize aggregate"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// HandleHistory retrieves the full event history for a Sample aggregate.
func (h *Handlers) HandleHistory(ctx context.Context, request protosource.Request) protosource.Response {
	id := extractID(request)
	if id == "" {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"missing required parameter: id"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	history, err := h.repo.History(ctx, id)
	if err != nil {
		if errors.Is(err, protosource.ErrAggregateNotFound) {
			return protosource.Response{
				StatusCode: http.StatusNotFound,
				Body:       `{"error":"aggregate not found"}`,
				Headers:    map[string]string{"Content-Type": "application/json"},
			}
		}
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"internal server error"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	body, err := protojson.Marshal(history)
	if err != nil {
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"failed to serialize history"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// extractID extracts the aggregate ID from path parameters or query string.
func extractID(request protosource.Request) string {
	if id, ok := request.PathParameters["id"]; ok && id != "" {
		return id
	}
	return request.QueryParameters["id"]
}

// commandErrorResponse maps protosource errors to appropriate HTTP responses.
func commandErrorResponse(err error) protosource.Response {
	statusCode := http.StatusInternalServerError
	message := "internal server error"

	switch {
	case errors.Is(err, protosource.ErrValidationFailed):
		statusCode = http.StatusBadRequest
		message = err.Error()
	case errors.Is(err, protosource.ErrEmptyAggregateId):
		statusCode = http.StatusBadRequest
		message = "aggregate id is required"
	case errors.Is(err, protosource.ErrAlreadyCreated):
		statusCode = http.StatusConflict
		message = "aggregate already exists"
	case errors.Is(err, protosource.ErrNotCreatedYet):
		statusCode = http.StatusNotFound
		message = "aggregate not found"
	case errors.Is(err, protosource.ErrAggregateNotFound):
		statusCode = http.StatusNotFound
		message = "aggregate not found"
	case errors.Is(err, protosource.ErrUnauthorized):
		statusCode = http.StatusForbidden
		message = "command not authorized"
	}

	return protosource.Response{
		StatusCode: statusCode,
		Body:       `{"error":"` + message + `"}`,
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// itoa converts an int64 to its string representation.
func itoa(n int64) string {
	if n == 0 {
		return "0"
	}
	neg := false
	if n < 0 {
		neg = true
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
