// Code generated by protoc-gen-protosource. DO NOT EDIT.

package samplev1

import (
	"context"
	"errors"
	"net/http"
	"strings"

	"github.com/funinthecloud/protosource"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// Handlers provides request handler functions for the Sample aggregate.
type Handlers struct {
	repo protosource.Repo
}

// NewHandlers creates a new Handlers instance with the given repository.
func NewHandlers(repo protosource.Repo) *Handlers {
	return &Handlers{repo: repo}
}

// RegisterRoutes registers all handler routes on the given router.
func (h *Handlers) RegisterRoutes(router *protosource.Router) {

	router.Handle("POST", "example/app/sample/v1/create", h.HandleCreate)

	router.Handle("POST", "example/app/sample/v1/update", h.HandleUpdate)

	router.Handle("GET", "example/app/sample/v1/{id}", h.HandleGet)
	router.Handle("GET", "example/app/sample/v1/{id}/history", h.HandleHistory)
}

// HandleCreate processes a Create command.
func (h *Handlers) HandleCreate(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &Create{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       `{"id":"` + cmd.GetId() + `","version":` + itoa(version) + `}`,
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// HandleUpdate processes a Update command.
func (h *Handlers) HandleUpdate(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &Update{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       `{"id":"` + cmd.GetId() + `","version":` + itoa(version) + `}`,
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// HandleGet retrieves the current state of a Sample aggregate.
func (h *Handlers) HandleGet(ctx context.Context, request protosource.Request) protosource.Response {
	id := extractID(request)
	if id == "" {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"missing required parameter: id"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	aggregate, err := h.repo.Load(ctx, id)
	if err != nil {
		if errors.Is(err, protosource.ErrAggregateNotFound) {
			return protosource.Response{
				StatusCode: http.StatusNotFound,
				Body:       `{"error":"aggregate not found"}`,
				Headers:    map[string]string{"Content-Type": "application/json"},
			}
		}
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"internal server error"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	body, contentType, err := marshalResponse(request, aggregate)
	if err != nil {
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"failed to serialize aggregate"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": contentType},
	}
}

// HandleHistory retrieves the full event history for a Sample aggregate.
func (h *Handlers) HandleHistory(ctx context.Context, request protosource.Request) protosource.Response {
	id := extractID(request)
	if id == "" {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"missing required parameter: id"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	history, err := h.repo.History(ctx, id)
	if err != nil {
		if errors.Is(err, protosource.ErrAggregateNotFound) {
			return protosource.Response{
				StatusCode: http.StatusNotFound,
				Body:       `{"error":"aggregate not found"}`,
				Headers:    map[string]string{"Content-Type": "application/json"},
			}
		}
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"internal server error"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	body, contentType, err := marshalResponse(request, history)
	if err != nil {
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"failed to serialize history"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": contentType},
	}
}

// acceptsProtobuf returns true if the Accept header includes application/protobuf.
func acceptsProtobuf(request protosource.Request) bool {
	accept := request.Headers["Accept"]
	if accept == "" {
		accept = request.Headers["accept"]
	}
	return strings.Contains(accept, "application/protobuf")
}

// isProtobufContent returns true if the Content-Type header indicates protobuf.
func isProtobufContent(request protosource.Request) bool {
	ct := request.Headers["Content-Type"]
	if ct == "" {
		ct = request.Headers["content-type"]
	}
	return strings.Contains(ct, "application/protobuf")
}

// unmarshalCommand decodes the request body into a proto message, using
// Content-Type to select protobuf binary or JSON deserialization.
func unmarshalCommand(request protosource.Request, msg proto.Message) error {
	if isProtobufContent(request) {
		return proto.Unmarshal([]byte(request.Body), msg)
	}
	return protojson.Unmarshal([]byte(request.Body), msg)
}

// marshalResponse encodes a proto message for the response, using the Accept
// header to select protobuf binary or JSON serialization. Returns the
// serialized bytes and the appropriate Content-Type.
func marshalResponse(request protosource.Request, msg proto.Message) ([]byte, string, error) {
	if acceptsProtobuf(request) {
		b, err := proto.Marshal(msg)
		return b, "application/protobuf", err
	}
	b, err := protojson.Marshal(msg)
	return b, "application/json", err
}

// extractID extracts the aggregate ID from path parameters or query string.
func extractID(request protosource.Request) string {
	if id, ok := request.PathParameters["id"]; ok && id != "" {
		return id
	}
	return request.QueryParameters["id"]
}

// commandErrorResponse maps protosource errors to appropriate HTTP responses.
func commandErrorResponse(err error) protosource.Response {
	statusCode := http.StatusInternalServerError
	message := "internal server error"

	switch {
	case errors.Is(err, protosource.ErrValidationFailed):
		statusCode = http.StatusBadRequest
		message = err.Error()
	case errors.Is(err, protosource.ErrEmptyAggregateId):
		statusCode = http.StatusBadRequest
		message = "aggregate id is required"
	case errors.Is(err, protosource.ErrAlreadyCreated):
		statusCode = http.StatusConflict
		message = "aggregate already exists"
	case errors.Is(err, protosource.ErrNotCreatedYet):
		statusCode = http.StatusNotFound
		message = "aggregate not found"
	case errors.Is(err, protosource.ErrAggregateNotFound):
		statusCode = http.StatusNotFound
		message = "aggregate not found"
	case errors.Is(err, protosource.ErrUnauthorized):
		statusCode = http.StatusForbidden
		message = "command not authorized"
	}

	return protosource.Response{
		StatusCode: statusCode,
		Body:       `{"error":"` + message + `"}`,
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// itoa converts an int64 to its string representation.
func itoa(n int64) string {
	if n == 0 {
		return "0"
	}
	neg := false
	if n < 0 {
		neg = true
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
