//go:build wireinject

// Code generated by protoc-gen-protosource. DO NOT EDIT.

package samplev1

import (
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/memorystore"
	"github.com/google/wire"
)

func provideStore() *memorystore.MemoryStore {
	return memorystore.New(memorystore.WithSnapshotInterval(SnapshotEveryNEvents))
}

func provideSerializer() *protobinaryserializer.Serializer {
	return protobinaryserializer.NewSerializer()
}

func provideRepository(store *memorystore.MemoryStore, serializer *protobinaryserializer.Serializer) *protosource.Repository {
	return NewRepository(protosource.WithStore(store), protosource.WithSerializer(serializer))
}

var ProviderSet = wire.NewSet(
	provideStore,
	provideSerializer,
	provideRepository,
	wire.Bind(new(protosource.Store), new(*memorystore.MemoryStore)),
	wire.Bind(new(protosource.Serializer), new(*protobinaryserializer.Serializer)),
	wire.Bind(new(protosource.Repo), new(*protosource.Repository)),
)
