// Code generated by protoc-gen-protosource. DO NOT EDIT.

package samplev1

import (
	"context"
	"fmt"
	"strconv"

	historyv1 "github.com/funinthecloud/protosource/history/v1"
	"github.com/funinthecloud/protosource/httpclient"
	responsev1 "github.com/funinthecloud/protosource/response/v1"
)

const routePath = "example/app/sample/v1"

// HTTPClient is a typed HTTP client for the Sample aggregate.
type HTTPClient struct {
	c httpclient.Doer
}

// NewHTTPClient creates a new Sample HTTP client.
// Accepts httpclient.Doer for testability — use *httpclient.Client in
// production and a mock in tests.
func NewHTTPClient(c httpclient.Doer) *HTTPClient {
	return &HTTPClient{c: c}
}

// Create sends the Create command.
func (c *HTTPClient) Create(ctx context.Context, id string, body string) (*responsev1.CommandResponse, error) {
	cmd := &Create{
		Id:   id,
		Body: body,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Update sends the Update command.
func (c *HTTPClient) Update(ctx context.Context, id string, body string) (*responsev1.CommandResponse, error) {
	cmd := &Update{
		Id:   id,
		Body: body,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Load retrieves the current state of the Sample aggregate via event replay.
func (c *HTTPClient) Load(ctx context.Context, id string) (*Sample, error) {
	agg := &Sample{}
	if err := c.c.Load(ctx, routePath, id, agg); err != nil {
		return nil, err
	}
	return agg, nil
}

// Get retrieves the Sample aggregate from the materialized store.
func (c *HTTPClient) Get(ctx context.Context, id string) (*Sample, error) {
	agg := &Sample{}
	if err := c.c.Get(ctx, routePath, id, agg); err != nil {
		return nil, err
	}
	return agg, nil
}

// History retrieves the full event history for the Sample aggregate.
func (c *HTTPClient) History(ctx context.Context, id string) (*historyv1.History, error) {
	return c.c.History(ctx, routePath, id)
}

// QueryByCreateBy queries by create_by via GSI1.
func (c *HTTPClient) QueryByCreateBy(ctx context.Context, createBy string) ([]*Sample, error) {
	params := map[string]string{
		"create_by": createBy,
	}
	list := &SampleList{}
	if err := c.c.Query(ctx, routePath, "by-create-by", params, list); err != nil {
		return nil, err
	}
	return list.Items, nil
}

// QueryByCreateByWithCreateAt queries with a sort key condition (eq, lt, le, gt, ge, begins_with).
// For between queries, use QueryByCreateByBetweenCreateAt instead.
func (c *HTTPClient) QueryByCreateByWithCreateAt(ctx context.Context, createBy string, skOp string, createAt int64) ([]*Sample, error) {
	if skOp == "between" {
		return nil, fmt.Errorf("use QueryByCreateByBetweenCreateAt for between queries")
	}
	params := map[string]string{
		"create_by": createBy,
		"sk_op":     skOp,
		"create_at": strconv.FormatInt(createAt, 10),
	}
	list := &SampleList{}
	if err := c.c.Query(ctx, routePath, "by-create-by", params, list); err != nil {
		return nil, err
	}
	return list.Items, nil
}

// QueryByCreateByBetweenCreateAt queries with a between sort key condition (inclusive range).
func (c *HTTPClient) QueryByCreateByBetweenCreateAt(ctx context.Context, createBy string, createAtFrom int64, createAtTo int64) ([]*Sample, error) {
	params := map[string]string{
		"create_by":  createBy,
		"sk_op":      "between",
		"create_at":  strconv.FormatInt(createAtFrom, 10),
		"create_at2": strconv.FormatInt(createAtTo, 10),
	}
	list := &SampleList{}
	if err := c.c.Query(ctx, routePath, "by-create-by", params, list); err != nil {
		return nil, err
	}
	return list.Items, nil
}

// Ensure strconv and fmt are used.
var _ = strconv.FormatInt
var _ = fmt.Errorf
