
// Code generated by protoc-gen-protosource-ts. DO NOT EDIT.

import type { ProtosourceClient, CommandResponse, History } from "@protosource/client";
import { CreateSchema, UpdateSchema, LockSchema, UnlockSchema, TestSchema, TestListSchema, State } from "./test_v1_pb.js";
import type { Create, Update, Lock, Unlock, Test, TestList } from "./test_v1_pb.js";

const routePath = "example/app/test/v1";

export class TestHTTPClient {
  private readonly client: ProtosourceClient;

  constructor(client: ProtosourceClient) {
    this.client = client;
  }

  async create(id: string, body: string, color: string, shape: string, number: string, shading: string): Promise<CommandResponse> {
    return this.client.apply(routePath, CreateSchema, { id, body, color, shape, number, shading });
  }

  async update(id: string, body: string, color: string, shape: string, number: string, shading: string): Promise<CommandResponse> {
    return this.client.apply(routePath, UpdateSchema, { id, body, color, shape, number, shading });
  }

  async lock(id: string): Promise<CommandResponse> {
    return this.client.apply(routePath, LockSchema, { id });
  }

  async unlock(id: string): Promise<CommandResponse> {
    return this.client.apply(routePath, UnlockSchema, { id });
  }

  async load(id: string): Promise<Test> {
    return this.client.load(routePath, id, TestSchema);
  }

  async get(id: string): Promise<Test> {
    return this.client.get(routePath, id, TestSchema);
  }

  async history(id: string): Promise<History> {
    return this.client.history(routePath, id);
  }

  async queryByColor(color: string): Promise<Test[]> {
    const params: Record<string, string> = {
      "color": color,
    };
    const list = await this.client.query(routePath, "by-color", params, TestListSchema);
    return list.items;
  }


  async queryByColorWithShape(color: string, skOp: string, shape: string): Promise<Test[]> {
    if (skOp === "between") {
      throw new Error("use queryByColorBetweenShape for between queries");
    }
    const params: Record<string, string> = {
      "color": color,
      "sk_op": skOp,
      "shape": shape,
    };
    const list = await this.client.query(routePath, "by-color", params, TestListSchema);
    return list.items;
  }

  async queryByColorBetweenShape(color: string, shapeFrom: string, shapeTo: string): Promise<Test[]> {
    const params: Record<string, string> = {
      "color": color,
      "sk_op": "between",
      "shape": shapeFrom,
      "shape2": shapeTo,
    };
    const list = await this.client.query(routePath, "by-color", params, TestListSchema);
    return list.items;
  }

  async queryByColorViaGSI2(color: string): Promise<Test[]> {
    const params: Record<string, string> = {
      "color": color,
    };
    const list = await this.client.query(routePath, "by-color-with-number", params, TestListSchema);
    return list.items;
  }


  async queryByColorWithNumber(color: string, skOp: string, number: string): Promise<Test[]> {
    if (skOp === "between") {
      throw new Error("use queryByColorBetweenNumber for between queries");
    }
    const params: Record<string, string> = {
      "color": color,
      "sk_op": skOp,
      "number": number,
    };
    const list = await this.client.query(routePath, "by-color-with-number", params, TestListSchema);
    return list.items;
  }

  async queryByColorBetweenNumber(color: string, numberFrom: string, numberTo: string): Promise<Test[]> {
    const params: Record<string, string> = {
      "color": color,
      "sk_op": "between",
      "number": numberFrom,
      "number2": numberTo,
    };
    const list = await this.client.query(routePath, "by-color-with-number", params, TestListSchema);
    return list.items;
  }

  async queryByNumberAndShading(number: string, shading: string): Promise<Test[]> {
    const params: Record<string, string> = {
      "number": number,
      "shading": shading,
    };
    const list = await this.client.query(routePath, "by-number-and-shading", params, TestListSchema);
    return list.items;
  }


  async queryByNumberAndShadingWithShapeAndCreateBy(number: string, shading: string, skOp: string, shape: string, createBy: string): Promise<Test[]> {
    if (skOp === "between") {
      throw new Error("use queryByNumberAndShadingBetweenShapeAndCreateBy for between queries");
    }
    const params: Record<string, string> = {
      "number": number,
      "shading": shading,
      "sk_op": skOp,
      "shape": shape,
      "create_by": createBy,
    };
    const list = await this.client.query(routePath, "by-number-and-shading", params, TestListSchema);
    return list.items;
  }

  async queryByNumberAndShadingBetweenShapeAndCreateBy(number: string, shading: string, shapeFrom: string, shapeTo: string, createByFrom: string, createByTo: string): Promise<Test[]> {
    const params: Record<string, string> = {
      "number": number,
      "shading": shading,
      "sk_op": "between",
      "shape": shapeFrom,
      "shape2": shapeTo,
      "create_by": createByFrom,
      "create_by2": createByTo,
    };
    const list = await this.client.query(routePath, "by-number-and-shading", params, TestListSchema);
    return list.items;
  }

  async queryByState(state: State): Promise<Test[]> {
    const params: Record<string, string> = {
      "state": String(state),
    };
    const list = await this.client.query(routePath, "by-state", params, TestListSchema);
    return list.items;
  }


  async queryByStateWithCreateAt(state: State, skOp: string, createAt: bigint): Promise<Test[]> {
    if (skOp === "between") {
      throw new Error("use queryByStateBetweenCreateAt for between queries");
    }
    const params: Record<string, string> = {
      "state": String(state),
      "sk_op": skOp,
      "create_at": String(createAt),
    };
    const list = await this.client.query(routePath, "by-state", params, TestListSchema);
    return list.items;
  }

  async queryByStateBetweenCreateAt(state: State, createAtFrom: bigint, createAtTo: bigint): Promise<Test[]> {
    const params: Record<string, string> = {
      "state": String(state),
      "sk_op": "between",
      "create_at": String(createAtFrom),
      "create_at2": String(createAtTo),
    };
    const list = await this.client.query(routePath, "by-state", params, TestListSchema);
    return list.items;
  }

}
