// Code generated by protoc-gen-protosource. DO NOT EDIT.
package main

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/user"
	"strconv"
	"strings"
	"time"

	pkg "github.com/funinthecloud/protosource/example/app/test/v1"
	historyv1 "github.com/funinthecloud/protosource/history/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"
)

var usage = "Usage: testmgr [-json] <command> [args]\n\nFlags:\n" +
	"  -json              Use JSON serialization (default: protobuf)\n\n" +
	"Commands:\n" +
	"  create  <id>  <body>\n" +
	"  update  <id>  <body>\n" +
	"  lock  <id>\n" +
	"  unlock  <id>\n" +
	"  load     <id>\n" +
	"  history  <id>\n" +
	"\nActor is derived automatically from the current user and hostname.\n\n" +
	"Environment variables:\n" +
	"  API_DOMAIN      Base domain for API endpoint (pattern: test-v1.API_DOMAIN)\n" +
	"  API_ENDPOINT    Full API endpoint URL (fallback if API_DOMAIN not set)\n"

var (
	useJSON     bool
	apiEndpoint string
	httpClient  = &http.Client{Timeout: 30 * time.Second}
)

func main() {
	// Parse flags
	for len(os.Args) > 1 && strings.HasPrefix(os.Args[1], "-") {
		switch os.Args[1] {
		case "-json":
			useJSON = true
			os.Args = append(os.Args[:1], os.Args[2:]...)
		default:
			fmt.Fprintln(os.Stderr, usage)
			os.Exit(1)
		}
	}

	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, usage)
		os.Exit(1)
	}

	// Resolve API endpoint
	if apiDomain := os.Getenv("API_DOMAIN"); apiDomain != "" {
		apiEndpoint = "https://test-v1." + apiDomain
	} else if endpoint := os.Getenv("API_ENDPOINT"); endpoint != "" {
		apiEndpoint = endpoint
	} else {
		fatal("Neither API_DOMAIN nor API_ENDPOINT is defined")
	}

	actor := detectActor()
	subcmd := os.Args[1]

	switch subcmd {

	case "create":
		if len(os.Args) != 4 {
			fatal("usage: testmgr create <id> <body>")
		}
		cmd := &pkg.Create{
			Id:    os.Args[2],
			Actor: actor,
			Body:  os.Args[3],
		}
		applyAndPrint(cmd)

	case "update":
		if len(os.Args) != 4 {
			fatal("usage: testmgr update <id> <body>")
		}
		cmd := &pkg.Update{
			Id:    os.Args[2],
			Actor: actor,
			Body:  os.Args[3],
		}
		applyAndPrint(cmd)

	case "lock":
		if len(os.Args) != 3 {
			fatal("usage: testmgr lock <id>")
		}
		cmd := &pkg.Lock{
			Id:    os.Args[2],
			Actor: actor,
		}
		applyAndPrint(cmd)

	case "unlock":
		if len(os.Args) != 3 {
			fatal("usage: testmgr unlock <id>")
		}
		cmd := &pkg.Unlock{
			Id:    os.Args[2],
			Actor: actor,
		}
		applyAndPrint(cmd)

	case "load":
		if len(os.Args) != 3 {
			fatal("usage: testmgr load <id>")
		}
		loadAggregate(os.Args[2])

	case "history":
		if len(os.Args) != 3 {
			fatal("usage: testmgr history <id>")
		}
		loadHistory(os.Args[2])

	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n%s\n", subcmd, usage)
		os.Exit(1)
	}
}

func applyAndPrint(cmd proto.Message) {
	// Serialize command
	var body []byte
	var contentType string
	var accept string

	if useJSON {
		b, err := protojson.Marshal(cmd)
		if err != nil {
			fatal(fmt.Sprintf("error marshaling command: %v", err))
		}
		body = b
		contentType = "application/json"
		accept = "application/json"
	} else {
		b, err := proto.Marshal(cmd)
		if err != nil {
			fatal(fmt.Sprintf("error marshaling command: %v", err))
		}
		body = b
		contentType = "application/protobuf"
		accept = "application/protobuf"
	}

	// Extract command name from type
	cmdName := strings.ToLower(string(cmd.ProtoReflect().Descriptor().Name()))
	url := apiEndpoint + "/example/app/test/v1/" + cmdName

	// Make request
	req, err := http.NewRequest("POST", url, bytes.NewReader(body))
	if err != nil {
		fatal(fmt.Sprintf("error creating request: %v", err))
	}
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Accept", accept)

	resp, err := httpClient.Do(req)
	if err != nil {
		fatal(fmt.Sprintf("error making request: %v", err))
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		fatal(fmt.Sprintf("error reading response: %v", err))
	}

	if resp.StatusCode >= 400 {
		fmt.Fprintf(os.Stderr, "error: %s\n", string(respBody))
		os.Exit(1)
	}

	// Command response is JSON {"id":"...","version":...}
	fmt.Println(string(respBody))
}

func loadAggregate(id string) {
	var accept string
	if useJSON {
		accept = "application/json"
	} else {
		accept = "application/protobuf"
	}

	url := apiEndpoint + "/example/app/test/v1/" + id
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		fatal(fmt.Sprintf("error creating request: %v", err))
	}
	req.Header.Set("Accept", accept)

	resp, err := httpClient.Do(req)
	if err != nil {
		fatal(fmt.Sprintf("error making request: %v", err))
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		fatal(fmt.Sprintf("error reading response: %v", err))
	}

	if resp.StatusCode >= 400 {
		fmt.Fprintf(os.Stderr, "error: %s\n", string(respBody))
		os.Exit(1)
	}

	agg := &pkg.Test{}
	if useJSON {
		if err := protojson.Unmarshal(respBody, agg); err != nil {
			fatal(fmt.Sprintf("error unmarshaling response: %v", err))
		}
	} else {
		if err := proto.Unmarshal(respBody, agg); err != nil {
			fatal(fmt.Sprintf("error unmarshaling response: %v", err))
		}
	}

	printAggregate(agg)
}

func loadHistory(id string) {
	var accept string
	if useJSON {
		accept = "application/json"
	} else {
		accept = "application/protobuf"
	}

	url := apiEndpoint + "/example/app/test/v1/" + id + "/history"
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		fatal(fmt.Sprintf("error creating request: %v", err))
	}
	req.Header.Set("Accept", accept)

	resp, err := httpClient.Do(req)
	if err != nil {
		fatal(fmt.Sprintf("error making request: %v", err))
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		fatal(fmt.Sprintf("error reading response: %v", err))
	}

	if resp.StatusCode >= 400 {
		fmt.Fprintf(os.Stderr, "error: %s\n", string(respBody))
		os.Exit(1)
	}

	history := &historyv1.History{}
	if useJSON {
		if err := protojson.Unmarshal(respBody, history); err != nil {
			fatal(fmt.Sprintf("error unmarshaling history: %v", err))
		}
	} else {
		if err := proto.Unmarshal(respBody, history); err != nil {
			fatal(fmt.Sprintf("error unmarshaling history: %v", err))
		}
	}

	for _, record := range history.GetRecords() {
		var a anypb.Any
		if err := proto.Unmarshal(record.GetData(), &a); err != nil {
			fmt.Fprintf(os.Stderr, "v%d: error unmarshaling record: %v\n", record.GetVersion(), err)
			continue
		}

		// Extract short type name from type URL
		typeName := a.GetTypeUrl()
		if i := strings.LastIndex(typeName, "."); i >= 0 {
			typeName = typeName[i+1:]
		}

		msg, err := a.UnmarshalNew()
		if err != nil {
			fmt.Fprintf(os.Stderr, "v%d %s: error unpacking: %v\n", record.GetVersion(), typeName, err)
			continue
		}

		b, err := jsonFormatter.Marshal(msg)
		if err != nil {
			fmt.Fprintf(os.Stderr, "v%d %s: error formatting: %v\n", record.GetVersion(), typeName, err)
			continue
		}

		fmt.Printf("v%d %s\n%s\n\n", record.GetVersion(), typeName, string(b))
	}
}

var jsonFormatter = protojson.MarshalOptions{Multiline: true, Indent: "  "}

func printAggregate(agg proto.Message) {
	b, err := jsonFormatter.Marshal(agg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error formatting aggregate: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(string(b))
}

func detectActor() string {
	username := "unknown"
	if u, err := user.Current(); err == nil {
		username = u.Username
	}
	hostname := "unknown"
	if h, err := os.Hostname(); err == nil {
		hostname = h
	}
	return username + "@" + hostname
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, msg)
	os.Exit(1)
}

// ── Scalar parsing helpers ──────────────────────────────────────────────────

func mustParseInt32(s, field string) int32 {
	v, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return int32(v)
}

func mustParseInt64(s, field string) int64 {
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return v
}

func mustParseUint32(s, field string) uint32 {
	v, err := strconv.ParseUint(s, 10, 32)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return uint32(v)
}

func mustParseUint64(s, field string) uint64 {
	v, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return v
}

func mustParseFloat(s string, bitSize int, field string) float64 {
	v, err := strconv.ParseFloat(s, bitSize)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return v
}

func mustParseBool(s, field string) bool {
	v, err := strconv.ParseBool(s)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return v
}

func mustReadFile(path, field string) []byte {
	b, err := os.ReadFile(path)
	if err != nil {
		fatal(fmt.Sprintf("cannot read file for %s: %v", field, err))
	}
	return b
}
