// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: funinthecloud/protosource/response/v1/response_v1.proto

package responsev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandResponse is the result of a successful command application.
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_funinthecloud_protosource_response_v1_response_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_response_v1_response_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_response_v1_response_v1_proto_rawDescGZIP(), []int{0}
}

func (x *CommandResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_funinthecloud_protosource_response_v1_response_v1_proto protoreflect.FileDescriptor

const file_funinthecloud_protosource_response_v1_response_v1_proto_rawDesc = "" +
	"\n" +
	"7funinthecloud/protosource/response/v1/response_v1.proto\x12%funinthecloud.protosource.response.v1\";\n" +
	"\x0fCommandResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversionB\xb0\x02\n" +
	")com.funinthecloud.protosource.response.v1B\x0fResponseV1ProtoP\x01Z;github.com/funinthecloud/protosource/response/v1;responsev1\xa2\x02\x03FPR\xaa\x02%Funinthecloud.Protosource.Response.V1\xca\x02%Funinthecloud\\Protosource\\Response\\V1\xe2\x021Funinthecloud\\Protosource\\Response\\V1\\GPBMetadata\xea\x02(Funinthecloud::Protosource::Response::V1b\x06proto3"

var (
	file_funinthecloud_protosource_response_v1_response_v1_proto_rawDescOnce sync.Once
	file_funinthecloud_protosource_response_v1_response_v1_proto_rawDescData []byte
)

func file_funinthecloud_protosource_response_v1_response_v1_proto_rawDescGZIP() []byte {
	file_funinthecloud_protosource_response_v1_response_v1_proto_rawDescOnce.Do(func() {
		file_funinthecloud_protosource_response_v1_response_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_response_v1_response_v1_proto_rawDesc), len(file_funinthecloud_protosource_response_v1_response_v1_proto_rawDesc)))
	})
	return file_funinthecloud_protosource_response_v1_response_v1_proto_rawDescData
}

var file_funinthecloud_protosource_response_v1_response_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_funinthecloud_protosource_response_v1_response_v1_proto_goTypes = []any{
	(*CommandResponse)(nil), // 0: funinthecloud.protosource.response.v1.CommandResponse
}
var file_funinthecloud_protosource_response_v1_response_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_funinthecloud_protosource_response_v1_response_v1_proto_init() }
func file_funinthecloud_protosource_response_v1_response_v1_proto_init() {
	if File_funinthecloud_protosource_response_v1_response_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_response_v1_response_v1_proto_rawDesc), len(file_funinthecloud_protosource_response_v1_response_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_funinthecloud_protosource_response_v1_response_v1_proto_goTypes,
		DependencyIndexes: file_funinthecloud_protosource_response_v1_response_v1_proto_depIdxs,
		MessageInfos:      file_funinthecloud_protosource_response_v1_response_v1_proto_msgTypes,
	}.Build()
	File_funinthecloud_protosource_response_v1_response_v1_proto = out.File
	file_funinthecloud_protosource_response_v1_response_v1_proto_goTypes = nil
	file_funinthecloud_protosource_response_v1_response_v1_proto_depIdxs = nil
}
