// Code generated by protoc-gen-protosource. DO NOT EDIT.
package main






    
        
        
    

    

    

    

    

    

    


import (
    "context"
    "fmt"
    "os"
    "os/user"
    "strconv"
    "strings"

    historyv1 "github.com/funinthecloud/protosource/history/v1"
    "github.com/funinthecloud/protosource/httpclient"
    pkg "github.com/funinthecloud/protosource/example/app/sample/v1"
    "google.golang.org/protobuf/encoding/protojson"
    "google.golang.org/protobuf/proto"
    "google.golang.org/protobuf/types/known/anypb"
)

var usage = "Usage: samplemgr [-json] <command> [args]\n\nFlags:\n" +
    "  -json              Use JSON serialization (default: protobuf)\n\n" +
    "Commands:\n" +
"  create  <id>  <body>\n" +
"  update  <id>  <body>\n" +
"  load     <id>\n" +
    "  history  <id>\n" +
    "\nActor is derived automatically from the current user and hostname.\n\n" +
    "Environment variables:\n" +
    "  API_DOMAIN      Base domain for API endpoint (pattern: sample-v1.API_DOMAIN)\n" +
    "  API_ENDPOINT    Full API endpoint URL (fallback if API_DOMAIN not set)\n"

func main() {
    var useJSON bool

    // Parse flags
    for len(os.Args) > 1 && strings.HasPrefix(os.Args[1], "-") {
        switch os.Args[1] {
        case "-json":
            useJSON = true
            os.Args = append(os.Args[:1], os.Args[2:]...)
        default:
            fmt.Fprintln(os.Stderr, usage)
            os.Exit(1)
        }
    }

    if len(os.Args) < 2 {
        fmt.Fprintln(os.Stderr, usage)
        os.Exit(1)
    }

    // Resolve API endpoint
    var apiEndpoint string
    if apiDomain := os.Getenv("API_DOMAIN"); apiDomain != "" {
        apiEndpoint = "https://sample-v1." + apiDomain
    } else if endpoint := os.Getenv("API_ENDPOINT"); endpoint != "" {
        apiEndpoint = endpoint
    } else {
        fatal("Neither API_DOMAIN nor API_ENDPOINT is defined")
    }

    // Create client
    auth := httpclient.NewNoAuth(detectActor())
    var opts []httpclient.Option
    if useJSON {
        opts = append(opts, httpclient.WithJSON())
    }
    client := pkg.NewHTTPClient(httpclient.New(apiEndpoint, auth, opts...))

    ctx := context.Background()
    subcmd := os.Args[1]

    switch subcmd {







    case "create":
        if len(os.Args) != 4 {
            fatal("usage: samplemgr create <id> <body>")
        }
        result, err := client.Create(ctx, os.Args[2], os.Args[3])
        if err != nil {
            fatal(fmt.Sprintf("error: %v", err))
        }
        fmt.Printf("{\"id\":%q,\"version\":%d}\n", result.GetId(), result.GetVersion())




    case "update":
        if len(os.Args) != 4 {
            fatal("usage: samplemgr update <id> <body>")
        }
        result, err := client.Update(ctx, os.Args[2], os.Args[3])
        if err != nil {
            fatal(fmt.Sprintf("error: %v", err))
        }
        fmt.Printf("{\"id\":%q,\"version\":%d}\n", result.GetId(), result.GetVersion())








    case "load":
        if len(os.Args) != 3 {
            fatal("usage: samplemgr load <id>")
        }
        agg, err := client.Load(ctx, os.Args[2])
        if err != nil {
            fatal(fmt.Sprintf("error: %v", err))
        }
        printProto(agg)

    case "history":
        if len(os.Args) != 3 {
            fatal("usage: samplemgr history <id>")
        }
        history, err := client.History(ctx, os.Args[2])
        if err != nil {
            fatal(fmt.Sprintf("error: %v", err))
        }
        printHistory(history)

    default:
        fmt.Fprintf(os.Stderr, "unknown command: %s\n\n%s\n", subcmd, usage)
        os.Exit(1)
    }
}

var jsonFormatter = protojson.MarshalOptions{Multiline: true, Indent: "  "}

func printProto(msg proto.Message) {
    b, err := jsonFormatter.Marshal(msg)
    if err != nil {
        fatal(fmt.Sprintf("error formatting: %v", err))
    }
    fmt.Println(string(b))
}

func printHistory(history *historyv1.History) {
    for _, record := range history.GetRecords() {
        var a anypb.Any
        if err := proto.Unmarshal(record.GetData(), &a); err != nil {
            fmt.Fprintf(os.Stderr, "v%d: error unmarshaling record: %v\n", record.GetVersion(), err)
            continue
        }

        typeName := a.GetTypeUrl()
        if i := strings.LastIndex(typeName, "."); i >= 0 {
            typeName = typeName[i+1:]
        }

        msg, err := a.UnmarshalNew()
        if err != nil {
            fmt.Fprintf(os.Stderr, "v%d %s: error unpacking: %v\n", record.GetVersion(), typeName, err)
            continue
        }

        b, err := jsonFormatter.Marshal(msg)
        if err != nil {
            fmt.Fprintf(os.Stderr, "v%d %s: error formatting: %v\n", record.GetVersion(), typeName, err)
            continue
        }

        fmt.Printf("v%d %s\n%s\n\n", record.GetVersion(), typeName, string(b))
    }
}

func detectActor() string {
    username := "unknown"
    if u, err := user.Current(); err == nil {
        username = u.Username
    }
    hostname := "unknown"
    if h, err := os.Hostname(); err == nil {
        hostname = h
    }
    return username + "@" + hostname
}

func fatal(msg string) {
    fmt.Fprintln(os.Stderr, msg)
    os.Exit(1)
}

// ── Scalar parsing helpers ──────────────────────────────────────────────────

func mustParseInt32(s, field string) int32 {
    v, err := strconv.ParseInt(s, 10, 32)
    if err != nil {
        fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
    }
    return int32(v)
}

func mustParseInt64(s, field string) int64 {
    v, err := strconv.ParseInt(s, 10, 64)
    if err != nil {
        fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
    }
    return v
}

func mustParseUint32(s, field string) uint32 {
    v, err := strconv.ParseUint(s, 10, 32)
    if err != nil {
        fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
    }
    return uint32(v)
}

func mustParseUint64(s, field string) uint64 {
    v, err := strconv.ParseUint(s, 10, 64)
    if err != nil {
        fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
    }
    return v
}

func mustParseFloat(s string, bitSize int, field string) float64 {
    v, err := strconv.ParseFloat(s, bitSize)
    if err != nil {
        fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
    }
    return v
}

func mustParseBool(s, field string) bool {
    v, err := strconv.ParseBool(s)
    if err != nil {
        fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
    }
    return v
}

func mustReadFile(path, field string) []byte {
    b, err := os.ReadFile(path)
    if err != nil {
        fatal(fmt.Sprintf("cannot read file for %s: %v", field, err))
    }
    return b
}
