
// Code generated by protoc-gen-protosource-ts. DO NOT EDIT.

import type { ProtosourceClient, CommandResponse, History } from "@protosource/client";
import { CreateSchema, AddItemSchema, RemoveItemSchema, AddTagSchema, RemoveTagSchema, SetShippingSchema, PlaceSchema, CancelSchema, OrderSchema, OrderListSchema } from "./order_v1_pb.js";
import type { Create, AddItem, RemoveItem, AddTag, RemoveTag, SetShipping, Place, Cancel, Order, OrderList, LineItem, Tag } from "./order_v1_pb.js";

const routePath = "example/app/order/v1";

export class OrderHTTPClient {
  private readonly client: ProtosourceClient;

  constructor(client: ProtosourceClient) {
    this.client = client;
  }

  async create(id: string, customerId: string, customerName: string): Promise<CommandResponse> {
    return this.client.apply(routePath, CreateSchema, { id, customerId, customerName });
  }

  async addItem(id: string, item: LineItem): Promise<CommandResponse> {
    return this.client.apply(routePath, AddItemSchema, { id, item });
  }

  async removeItem(id: string, itemId: string): Promise<CommandResponse> {
    return this.client.apply(routePath, RemoveItemSchema, { id, itemId });
  }

  async addTag(id: string, tag: Tag): Promise<CommandResponse> {
    return this.client.apply(routePath, AddTagSchema, { id, tag });
  }

  async removeTag(id: string, key: string): Promise<CommandResponse> {
    return this.client.apply(routePath, RemoveTagSchema, { id, key });
  }

  async setShipping(id: string, shippingAddress: string): Promise<CommandResponse> {
    return this.client.apply(routePath, SetShippingSchema, { id, shippingAddress });
  }

  async place(id: string, placedAt: bigint): Promise<CommandResponse> {
    return this.client.apply(routePath, PlaceSchema, { id, placedAt });
  }

  async cancel(id: string, reason: string): Promise<CommandResponse> {
    return this.client.apply(routePath, CancelSchema, { id, reason });
  }

  async load(id: string): Promise<Order> {
    return this.client.load(routePath, id, OrderSchema);
  }

  async get(id: string): Promise<Order> {
    return this.client.get(routePath, id, OrderSchema);
  }

  async history(id: string): Promise<History> {
    return this.client.history(routePath, id);
  }

  async queryByCustomerId(customerId: string): Promise<Order[]> {
    const params: Record<string, string> = {
      "customer_id": customerId,
    };
    const list = await this.client.query(routePath, "by-customer-id", params, OrderListSchema);
    return list.items;
  }


  async queryByCustomerIdWithCreateAt(customerId: string, skOp: string, createAt: bigint): Promise<Order[]> {
    if (skOp === "between") {
      throw new Error("use queryByCustomerIdBetweenCreateAt for between queries");
    }
    const params: Record<string, string> = {
      "customer_id": customerId,
      "sk_op": skOp,
      "create_at": String(createAt),
    };
    const list = await this.client.query(routePath, "by-customer-id", params, OrderListSchema);
    return list.items;
  }

  async queryByCustomerIdBetweenCreateAt(customerId: string, createAtFrom: bigint, createAtTo: bigint): Promise<Order[]> {
    const params: Record<string, string> = {
      "customer_id": customerId,
      "sk_op": "between",
      "create_at": String(createAtFrom),
      "create_at2": String(createAtTo),
    };
    const list = await this.client.query(routePath, "by-customer-id", params, OrderListSchema);
    return list.items;
  }

}
