// Code generated by protoc-gen-protosource. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"os"
	"os/user"
	"strconv"
	"text/tabwriter"
	"time"

	"github.com/funinthecloud/protosource"
	pkg "github.com/funinthecloud/protosource/example/app/order/v1"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/boltdbstore"
	"google.golang.org/protobuf/encoding/protojson"
)

var usage = "Usage: ordermgr <command> [args]\n\nCommands:\n" +
	"  create  <id>  <customerid>  <customername>\n" +
	"  additem  <id>  <description>  <pricecents>  <quantity>\n" +
	"  setshipping  <id>  <shippingaddress>\n" +
	"  place  <id>\n" +
	"  cancel  <id>  <reason>\n" +
	"  load     <id>\n" +
	"  history  <id>\n" +
	"\nActor is derived automatically from the current user and hostname.\n"

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, usage)
		os.Exit(1)
	}

	store, err := boltdbstore.New("./data/order", "order")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error opening store: %v\n", err)
		os.Exit(1)
	}
	defer store.Close()

	serializer := protobinaryserializer.NewSerializer()
	repo := pkg.NewRepository(store, serializer)

	actor := detectActor()
	ctx := context.Background()
	subcmd := os.Args[1]

	switch subcmd {

	case "create":
		if len(os.Args) != 5 {
			fatal("usage: ordermgr create <id> <customerid> <customername>")
		}
		cmd := &pkg.Create{
			Id:           os.Args[2],
			Actor:        actor,
			CustomerId:   os.Args[3],
			CustomerName: os.Args[4],
		}
		applyAndPrint(ctx, repo, cmd)

	case "additem":
		if len(os.Args) != 6 {
			fatal("usage: ordermgr additem <id> <description> <pricecents> <quantity>")
		}
		cmd := &pkg.AddItem{
			Id:          os.Args[2],
			Actor:       actor,
			Description: os.Args[3],
			PriceCents:  mustParseInt64(os.Args[4], "price_cents"),
			Quantity:    mustParseInt32(os.Args[5], "quantity"),
		}
		applyAndPrint(ctx, repo, cmd)

	case "setshipping":
		if len(os.Args) != 4 {
			fatal("usage: ordermgr setshipping <id> <shippingaddress>")
		}
		cmd := &pkg.SetShipping{
			Id:              os.Args[2],
			Actor:           actor,
			ShippingAddress: os.Args[3],
		}
		applyAndPrint(ctx, repo, cmd)

	case "place":
		if len(os.Args) != 3 {
			fatal("usage: ordermgr place <id>")
		}
		cmd := &pkg.Place{
			Id:    os.Args[2],
			Actor: actor,
		}
		applyAndPrint(ctx, repo, cmd)

	case "cancel":
		if len(os.Args) != 4 {
			fatal("usage: ordermgr cancel <id> <reason>")
		}
		cmd := &pkg.Cancel{
			Id:     os.Args[2],
			Actor:  actor,
			Reason: os.Args[3],
		}
		applyAndPrint(ctx, repo, cmd)

	case "load":
		if len(os.Args) != 3 {
			fatal("usage: ordermgr load <id>")
		}
		agg, err := repo.Load(ctx, os.Args[2])
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
		printAggregate(agg)

	case "history":
		if len(os.Args) != 3 {
			fatal("usage: ordermgr history <id>")
		}
		hist, err := repo.History(ctx, os.Args[2])
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("History: %d record(s)\n\n", len(hist.GetRecords()))
		w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
		fmt.Fprintln(w, "VERSION\tEVENT\tACTOR\tAT\tBYTES")
		fmt.Fprintln(w, "-------\t-----\t-----\t--\t-----")
		for _, rec := range hist.GetRecords() {
			event, err := serializer.UnmarshalEvent(rec)
			if err != nil {
				fmt.Fprintf(w, "%d\t(error)\t\t\t%d\n", rec.GetVersion(), len(rec.GetData()))
				continue
			}
			name := string(event.ProtoReflect().Descriptor().Name())
			fmt.Fprintf(w, "%d\t%s\t%s\t%s\t%d\n",
				event.GetVersion(), name, event.GetActor(),
				formatMicros(event.GetAt()), len(rec.GetData()))
		}
		w.Flush()

	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n%s\n", subcmd, usage)
		os.Exit(1)
	}
}

func applyAndPrint(ctx context.Context, repo *protosource.Repository, cmd protosource.Commander) {
	if _, err := repo.Apply(ctx, cmd); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	agg, err := repo.Load(ctx, cmd.GetId())
	if err != nil {
		fmt.Fprintf(os.Stderr, "error loading after apply: %v\n", err)
		os.Exit(1)
	}
	printAggregate(agg)
}

var jsonFormatter = protojson.MarshalOptions{Multiline: true, Indent: "  "}

func printAggregate(agg protosource.Aggregate) {
	b, err := jsonFormatter.Marshal(agg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error formatting aggregate: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(string(b))
}

func formatMicros(us int64) string {
	if us == 0 {
		return "(none)"
	}
	return time.UnixMicro(us).Format(time.RFC3339)
}

func detectActor() string {
	username := "unknown"
	if u, err := user.Current(); err == nil {
		username = u.Username
	}
	hostname := "unknown"
	if h, err := os.Hostname(); err == nil {
		hostname = h
	}
	return username + "@" + hostname
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, msg)
	os.Exit(1)
}

// ── Scalar parsing helpers ──────────────────────────────────────────────────

func mustParseInt32(s, field string) int32 {
	v, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return int32(v)
}

func mustParseInt64(s, field string) int64 {
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return v
}

func mustParseUint32(s, field string) uint32 {
	v, err := strconv.ParseUint(s, 10, 32)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return uint32(v)
}

func mustParseUint64(s, field string) uint64 {
	v, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return v
}

func mustParseFloat(s string, bitSize int, field string) float64 {
	v, err := strconv.ParseFloat(s, bitSize)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return v
}

func mustParseBool(s, field string) bool {
	v, err := strconv.ParseBool(s)
	if err != nil {
		fatal(fmt.Sprintf("invalid value for %s: %v", field, err))
	}
	return v
}

func mustReadFile(path, field string) []byte {
	b, err := os.ReadFile(path)
	if err != nil {
		fatal(fmt.Sprintf("cannot read file for %s: %v", field, err))
	}
	return b
}
