// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource/example/app/order/v1"
	"github.com/funinthecloud/protosource/example/app/order/v1/orderv1dynamodb"
	"github.com/funinthecloud/protosource/example/app/sample/v1"
	"github.com/funinthecloud/protosource/example/app/sample/v1/samplev1dynamodb"
	"github.com/funinthecloud/protosource/example/app/test/v1"
	"github.com/funinthecloud/protosource/example/app/test/v1/testv1dynamodb"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/dynamodbstore"
)

// Injectors from wire.go:

// InitializeRouter wires all dependencies and returns a configured router.
func InitializeRouter(client *dynamodb.Client, eventsTable dynamodbstore.EventsTableName, aggregatesTable dynamodbstore.AggregatesTableName) (*protosource.Router, error) {
	store := dynamodbstore.ProvideOpaqueStore(client, aggregatesTable)
	dynamoDBStore, err := dynamodbstore.ProvideStore(client, store, eventsTable)
	if err != nil {
		return nil, err
	}
	serializer := protobinaryserializer.NewSerializer()
	repository := testv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	handler := testv1.NewHandler(repository)
	orderv1dynamodbRepository := orderv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	orderv1Handler := orderv1.NewHandler(orderv1dynamodbRepository)
	samplev1dynamodbRepository := samplev1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	samplev1Handler := samplev1.NewHandler(samplev1dynamodbRepository)
	router := provideRouter(handler, orderv1Handler, samplev1Handler)
	return router, nil
}

// wire.go:

func provideRouter(
	testHandler *testv1.Handler,
	orderHandler *orderv1.Handler,
	sampleHandler *samplev1.Handler,
) *protosource.Router {
	return protosource.NewRouter(testHandler, orderHandler, sampleHandler)
}
