//go:build wireinject

// Code generated by protoc-gen-protosource. DO NOT EDIT.

package orderv1memory

import (
	"github.com/funinthecloud/protosource"
	pkg "github.com/funinthecloud/protosource/example/app/order/v1"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/memorystore"
	"github.com/google/wire"
)

func provideStore() *memorystore.MemoryStore {
	return memorystore.New(pkg.SnapshotEveryNEvents)
}

func provideRepository(store *memorystore.MemoryStore, serializer *protobinaryserializer.Serializer) *protosource.Repository {
	return pkg.NewRepository(store, serializer)
}

var ProviderSet = wire.NewSet(
	provideStore,
	memorystore.ProviderSet,
	protobinaryserializer.ProviderSet,
	provideRepository,
)
