// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: example/app/order/v1/order_v1.proto

package orderv1

import (
	_ "github.com/funinthecloud/protosource/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_DRAFT       State = 1
	State_STATE_PLACED      State = 2
	State_STATE_PAID        State = 3
	State_STATE_SHIPPED     State = 4
	State_STATE_DELIVERED   State = 5
	State_STATE_CANCELLED   State = 6
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_DRAFT",
		2: "STATE_PLACED",
		3: "STATE_PAID",
		4: "STATE_SHIPPED",
		5: "STATE_DELIVERED",
		6: "STATE_CANCELLED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_DRAFT":       1,
		"STATE_PLACED":      2,
		"STATE_PAID":        3,
		"STATE_SHIPPED":     4,
		"STATE_DELIVERED":   5,
		"STATE_CANCELLED":   6,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_example_app_order_v1_order_v1_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_example_app_order_v1_order_v1_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	State           State                  `protobuf:"varint,3,opt,name=state,proto3,enum=example.app.order.v1.State" json:"state,omitempty"`
	CustomerId      string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName    string                 `protobuf:"bytes,5,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CreateAt        int64                  `protobuf:"varint,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	CreateBy        string                 `protobuf:"bytes,7,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	ModifyAt        int64                  `protobuf:"varint,8,opt,name=modify_at,json=modifyAt,proto3" json:"modify_at,omitempty"`
	ModifyBy        string                 `protobuf:"bytes,9,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	TotalCents      int64                  `protobuf:"varint,10,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	ItemCount       int32                  `protobuf:"varint,11,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,12,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	PlacedAt        int64                  `protobuf:"varint,13,opt,name=placed_at,json=placedAt,proto3" json:"placed_at,omitempty"`
	Items           map[string]*LineItem   `protobuf:"bytes,14,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags            map[string]*Tag        `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Order) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Order) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Order) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *Order) GetModifyAt() int64 {
	if x != nil {
		return x.ModifyAt
	}
	return 0
}

func (x *Order) GetModifyBy() string {
	if x != nil {
		return x.ModifyBy
	}
	return ""
}

func (x *Order) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Order) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *Order) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *Order) GetPlacedAt() int64 {
	if x != nil {
		return x.PlacedAt
	}
	return 0
}

func (x *Order) GetItems() map[string]*LineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTags() map[string]*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type OrderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Order               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{1}
}

func (x *OrderList) GetItems() []*Order {
	if x != nil {
		return x.Items
	}
	return nil
}

// LineItem is a value type representing a single item in an order.
type LineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    int64                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{2}
}

func (x *LineItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *LineItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LineItem) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *LineItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Tag is a key-value label on an order (e.g. "priority"="rush", "source"="web").
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{3}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,4,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{4}
}

func (x *Create) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Create) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Create) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Create) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type AddItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Item          *LineItem              `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItem) Reset() {
	*x = AddItem{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItem) ProtoMessage() {}

func (x *AddItem) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItem.ProtoReflect.Descriptor instead.
func (*AddItem) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{5}
}

func (x *AddItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddItem) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AddItem) GetItem() *LineItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type RemoveItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItem) Reset() {
	*x = RemoveItem{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItem) ProtoMessage() {}

func (x *RemoveItem) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItem.ProtoReflect.Descriptor instead.
func (*RemoveItem) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveItem) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *RemoveItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type AddTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Tag           *Tag                   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTag) Reset() {
	*x = AddTag{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTag) ProtoMessage() {}

func (x *AddTag) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTag.ProtoReflect.Descriptor instead.
func (*AddTag) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{7}
}

func (x *AddTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddTag) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AddTag) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type RemoveTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTag) Reset() {
	*x = RemoveTag{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTag) ProtoMessage() {}

func (x *RemoveTag) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTag.ProtoReflect.Descriptor instead.
func (*RemoveTag) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveTag) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *RemoveTag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetShipping struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor           string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,3,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetShipping) Reset() {
	*x = SetShipping{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetShipping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetShipping) ProtoMessage() {}

func (x *SetShipping) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetShipping.ProtoReflect.Descriptor instead.
func (*SetShipping) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{9}
}

func (x *SetShipping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetShipping) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *SetShipping) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

type Place struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	PlacedAt      int64                  `protobuf:"varint,3,opt,name=placed_at,json=placedAt,proto3" json:"placed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Place) Reset() {
	*x = Place{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{10}
}

func (x *Place) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Place) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Place) GetPlacedAt() int64 {
	if x != nil {
		return x.PlacedAt
	}
	return 0
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{11}
}

func (x *Cancel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cancel) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Cancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Created struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	CustomerId    string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,6,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Created) Reset() {
	*x = Created{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Created) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Created) ProtoMessage() {}

func (x *Created) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Created.ProtoReflect.Descriptor instead.
func (*Created) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{12}
}

func (x *Created) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Created) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Created) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Created) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Created) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Created) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type ItemAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Item          *LineItem              `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAdded) Reset() {
	*x = ItemAdded{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAdded) ProtoMessage() {}

func (x *ItemAdded) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAdded.ProtoReflect.Descriptor instead.
func (*ItemAdded) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{13}
}

func (x *ItemAdded) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemAdded) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ItemAdded) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *ItemAdded) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ItemAdded) GetItem() *LineItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ItemRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	ItemId        string                 `protobuf:"bytes,5,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRemoved) Reset() {
	*x = ItemRemoved{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRemoved) ProtoMessage() {}

func (x *ItemRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRemoved.ProtoReflect.Descriptor instead.
func (*ItemRemoved) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{14}
}

func (x *ItemRemoved) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemRemoved) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ItemRemoved) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *ItemRemoved) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ItemRemoved) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type TagAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Tag           *Tag                   `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagAdded) Reset() {
	*x = TagAdded{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagAdded) ProtoMessage() {}

func (x *TagAdded) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagAdded.ProtoReflect.Descriptor instead.
func (*TagAdded) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{15}
}

func (x *TagAdded) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagAdded) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TagAdded) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *TagAdded) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *TagAdded) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type TagRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagRemoved) Reset() {
	*x = TagRemoved{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagRemoved) ProtoMessage() {}

func (x *TagRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagRemoved.ProtoReflect.Descriptor instead.
func (*TagRemoved) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{16}
}

func (x *TagRemoved) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagRemoved) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TagRemoved) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *TagRemoved) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *TagRemoved) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ShippingSet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At              int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor           string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,5,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShippingSet) Reset() {
	*x = ShippingSet{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingSet) ProtoMessage() {}

func (x *ShippingSet) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingSet.ProtoReflect.Descriptor instead.
func (*ShippingSet) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ShippingSet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShippingSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ShippingSet) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *ShippingSet) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ShippingSet) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

type Placed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	PlacedAt      int64                  `protobuf:"varint,5,opt,name=placed_at,json=placedAt,proto3" json:"placed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placed) Reset() {
	*x = Placed{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placed) ProtoMessage() {}

func (x *Placed) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placed.ProtoReflect.Descriptor instead.
func (*Placed) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{18}
}

func (x *Placed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Placed) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Placed) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Placed) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Placed) GetPlacedAt() int64 {
	if x != nil {
		return x.PlacedAt
	}
	return 0
}

type Cancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancelled) Reset() {
	*x = Cancelled{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancelled) ProtoMessage() {}

func (x *Cancelled) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancelled.ProtoReflect.Descriptor instead.
func (*Cancelled) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{19}
}

func (x *Cancelled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cancelled) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Cancelled) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Cancelled) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Cancelled) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// OrderSummary is a lightweight view of the Order for listings and dashboards.
// Fields are a subset of the aggregate — matched by name, copied automatically.
// PK is the same as the aggregate; SK = "PROJ#OrderSummary".
// GSI2 provides a status+placed_at index not present on the aggregate itself.
type OrderSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         State                  `protobuf:"varint,2,opt,name=state,proto3,enum=example.app.order.v1.State" json:"state,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,4,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	TotalCents    int64                  `protobuf:"varint,5,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	ItemCount     int32                  `protobuf:"varint,6,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	PlacedAt      int64                  `protobuf:"varint,7,opt,name=placed_at,json=placedAt,proto3" json:"placed_at,omitempty"`
	CreateAt      int64                  `protobuf:"varint,8,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSummary) Reset() {
	*x = OrderSummary{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSummary) ProtoMessage() {}

func (x *OrderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSummary.ProtoReflect.Descriptor instead.
func (*OrderSummary) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{20}
}

func (x *OrderSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderSummary) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *OrderSummary) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderSummary) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *OrderSummary) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *OrderSummary) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *OrderSummary) GetPlacedAt() int64 {
	if x != nil {
		return x.PlacedAt
	}
	return 0
}

func (x *OrderSummary) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Snapshot      *Order                 `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_order_v1_order_v1_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_example_app_order_v1_order_v1_proto_rawDescGZIP(), []int{21}
}

func (x *Snapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Snapshot) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Snapshot) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Snapshot) GetSnapshot() *Order {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_example_app_order_v1_order_v1_proto protoreflect.FileDescriptor

const file_example_app_order_v1_order_v1_proto_rawDesc = "" +
	"\n" +
	"#example/app/order/v1/order_v1.proto\x12\x14example.app.order.v1\x1a5funinthecloud/protosource/options/v1/options_v1.proto\"\xe8\x05\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x121\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1b.example.app.order.v1.StateR\x05state\x12*\n" +
	"\vcustomer_id\x18\x04 \x01(\tB\t\xaaP\x06\n" +
	"\x04\b\x03\x10\x01R\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x05 \x01(\tR\fcustomerName\x12$\n" +
	"\tcreate_at\x18\x06 \x01(\x03B\a\xaaP\x04\n" +
	"\x02\b\x04R\bcreateAt\x12\x1b\n" +
	"\tcreate_by\x18\a \x01(\tR\bcreateBy\x12\x1b\n" +
	"\tmodify_at\x18\b \x01(\x03R\bmodifyAt\x12\x1b\n" +
	"\tmodify_by\x18\t \x01(\tR\bmodifyBy\x12\x1f\n" +
	"\vtotal_cents\x18\n" +
	" \x01(\x03R\n" +
	"totalCents\x12\x1d\n" +
	"\n" +
	"item_count\x18\v \x01(\x05R\titemCount\x12)\n" +
	"\x10shipping_address\x18\f \x01(\tR\x0fshippingAddress\x12\x1b\n" +
	"\tplaced_at\x18\r \x01(\x03R\bplacedAt\x12<\n" +
	"\x05items\x18\x0e \x03(\v2&.example.app.order.v1.Order.ItemsEntryR\x05items\x129\n" +
	"\x04tags\x18\x0f \x03(\v2%.example.app.order.v1.Order.TagsEntryR\x04tags\x1aX\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.example.app.order.v1.LineItemR\x05value:\x028\x01\x1aR\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.example.app.order.v1.TagR\x05value:\x028\x01:\x05\xb2P\x02\x1a\x00\">\n" +
	"\tOrderList\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.example.app.order.v1.OrderR\x05items\"\x82\x01\n" +
	"\bLineItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x03R\n" +
	"priceCents\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x86\x01\n" +
	"\x06Create\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x04 \x01(\tR\fcustomerName:\x10\xb2P\r\n" +
	"\v\n" +
	"\aCreated\x10\x01\"\x84\x01\n" +
	"\aAddItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x122\n" +
	"\x04item\x18\x03 \x01(\v2\x1e.example.app.order.v1.LineItemR\x04item:\x1f\xb2P\x1c\n" +
	"\x1a\n" +
	"\tItemAdded\x10\x02\x1a\vSTATE_DRAFT\"n\n" +
	"\n" +
	"RemoveItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId:!\xb2P\x1e\n" +
	"\x1c\n" +
	"\vItemRemoved\x10\x02\x1a\vSTATE_DRAFT\"{\n" +
	"\x06AddTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12+\n" +
	"\x03tag\x18\x03 \x01(\v2\x19.example.app.order.v1.TagR\x03tag:\x1e\xb2P\x1b\n" +
	"\x19\n" +
	"\bTagAdded\x10\x02\x1a\vSTATE_DRAFT\"e\n" +
	"\tRemoveTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key: \xb2P\x1d\n" +
	"\x1b\n" +
	"\n" +
	"TagRemoved\x10\x02\x1a\vSTATE_DRAFT\"\x81\x01\n" +
	"\vSetShipping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12)\n" +
	"\x10shipping_address\x18\x03 \x01(\tR\x0fshippingAddress:!\xb2P\x1e\n" +
	"\x1c\n" +
	"\vShippingSet\x10\x02\x1a\vSTATE_DRAFT\"h\n" +
	"\x05Place\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x1b\n" +
	"\tplaced_at\x18\x03 \x01(\x03R\bplacedAt:\x1c\xb2P\x19\n" +
	"\x17\n" +
	"\x06Placed\x10\x02\x1a\vSTATE_DRAFT\"\x81\x01\n" +
	"\x06Cancel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason:9\xb2P6\n" +
	"4\n" +
	"\tCancelled\x10\x02\x1a\vSTATE_DRAFT\x1a\fSTATE_PLACED\x1a\n" +
	"STATE_PAID\"\xb3\x01\n" +
	"\aCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x06 \x01(\tR\fcustomerName:\x12\xb2P\x0f\x12\r\x12\vSTATE_DRAFT\"\xaa\x01\n" +
	"\tItemAdded\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x122\n" +
	"\x04item\x18\x05 \x01(\v2\x1e.example.app.order.v1.LineItemR\x04item:\x19\xb2P\x16\x12\x14\x1a\x12\n" +
	"\x05items\x10\x01\x1a\aitem_id\"\x91\x01\n" +
	"\vItemRemoved\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x17\n" +
	"\aitem_id\x18\x05 \x01(\tR\x06itemId:\x19\xb2P\x16\x12\x14\x1a\x12\n" +
	"\x05items\x10\x02\x1a\aitem_id\"\x9d\x01\n" +
	"\bTagAdded\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12+\n" +
	"\x03tag\x18\x05 \x01(\v2\x19.example.app.order.v1.TagR\x03tag:\x14\xb2P\x11\x12\x0f\x1a\r\n" +
	"\x04tags\x10\x01\x1a\x03key\"\x84\x01\n" +
	"\n" +
	"TagRemoved\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key:\x14\xb2P\x11\x12\x0f\x1a\r\n" +
	"\x04tags\x10\x02\x1a\x03key\"\x8f\x01\n" +
	"\vShippingSet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12)\n" +
	"\x10shipping_address\x18\x05 \x01(\tR\x0fshippingAddress:\x05\xb2P\x02\x12\x00\"\x8a\x01\n" +
	"\x06Placed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x1b\n" +
	"\tplaced_at\x18\x05 \x01(\x03R\bplacedAt:\x13\xb2P\x10\x12\x0e\x12\fSTATE_PLACED\"\x8b\x01\n" +
	"\tCancelled\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason:\x16\xb2P\x13\x12\x11\x12\x0fSTATE_CANCELLED\"\xc0\x02\n" +
	"\fOrderSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1b.example.app.order.v1.StateB\t\xaaP\x06\n" +
	"\x04\b\x05\x10\x01R\x05state\x12*\n" +
	"\vcustomer_id\x18\x03 \x01(\tB\t\xaaP\x06\n" +
	"\x04\b\x03\x10\x01R\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x04 \x01(\tR\fcustomerName\x12\x1f\n" +
	"\vtotal_cents\x18\x05 \x01(\x03R\n" +
	"totalCents\x12\x1d\n" +
	"\n" +
	"item_count\x18\x06 \x01(\x05R\titemCount\x12$\n" +
	"\tplaced_at\x18\a \x01(\x03B\a\xaaP\x04\n" +
	"\x02\b\x06R\bplacedAt\x12$\n" +
	"\tcreate_at\x18\b \x01(\x03B\a\xaaP\x04\n" +
	"\x02\b\x04R\bcreateAt:\x05\xb2P\x02\"\x00\"\x9c\x01\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x127\n" +
	"\bsnapshot\x18\x05 \x01(\v2\x1b.example.app.order.v1.OrderR\bsnapshot:\a\xb2P\x04*\x02\b2*\x8e\x01\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATE_DRAFT\x10\x01\x12\x10\n" +
	"\fSTATE_PLACED\x10\x02\x12\x0e\n" +
	"\n" +
	"STATE_PAID\x10\x03\x12\x11\n" +
	"\rSTATE_SHIPPED\x10\x04\x12\x13\n" +
	"\x0fSTATE_DELIVERED\x10\x05\x12\x13\n" +
	"\x0fSTATE_CANCELLED\x10\x06B\xe3\x01\xbaP\x02\b\x01\n" +
	"\x18com.example.app.order.v1B\fOrderV1ProtoP\x01ZAgithub.com/funinthecloud/protosource/example/app/order/v1;orderv1\xa2\x02\x03EAO\xaa\x02\x14Example.App.Order.V1\xca\x02\x14Example\\App\\Order\\V1\xe2\x02 Example\\App\\Order\\V1\\GPBMetadata\xea\x02\x17Example::App::Order::V1b\x06proto3"

var (
	file_example_app_order_v1_order_v1_proto_rawDescOnce sync.Once
	file_example_app_order_v1_order_v1_proto_rawDescData []byte
)

func file_example_app_order_v1_order_v1_proto_rawDescGZIP() []byte {
	file_example_app_order_v1_order_v1_proto_rawDescOnce.Do(func() {
		file_example_app_order_v1_order_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_app_order_v1_order_v1_proto_rawDesc), len(file_example_app_order_v1_order_v1_proto_rawDesc)))
	})
	return file_example_app_order_v1_order_v1_proto_rawDescData
}

var file_example_app_order_v1_order_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_app_order_v1_order_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_example_app_order_v1_order_v1_proto_goTypes = []any{
	(State)(0),           // 0: example.app.order.v1.State
	(*Order)(nil),        // 1: example.app.order.v1.Order
	(*OrderList)(nil),    // 2: example.app.order.v1.OrderList
	(*LineItem)(nil),     // 3: example.app.order.v1.LineItem
	(*Tag)(nil),          // 4: example.app.order.v1.Tag
	(*Create)(nil),       // 5: example.app.order.v1.Create
	(*AddItem)(nil),      // 6: example.app.order.v1.AddItem
	(*RemoveItem)(nil),   // 7: example.app.order.v1.RemoveItem
	(*AddTag)(nil),       // 8: example.app.order.v1.AddTag
	(*RemoveTag)(nil),    // 9: example.app.order.v1.RemoveTag
	(*SetShipping)(nil),  // 10: example.app.order.v1.SetShipping
	(*Place)(nil),        // 11: example.app.order.v1.Place
	(*Cancel)(nil),       // 12: example.app.order.v1.Cancel
	(*Created)(nil),      // 13: example.app.order.v1.Created
	(*ItemAdded)(nil),    // 14: example.app.order.v1.ItemAdded
	(*ItemRemoved)(nil),  // 15: example.app.order.v1.ItemRemoved
	(*TagAdded)(nil),     // 16: example.app.order.v1.TagAdded
	(*TagRemoved)(nil),   // 17: example.app.order.v1.TagRemoved
	(*ShippingSet)(nil),  // 18: example.app.order.v1.ShippingSet
	(*Placed)(nil),       // 19: example.app.order.v1.Placed
	(*Cancelled)(nil),    // 20: example.app.order.v1.Cancelled
	(*OrderSummary)(nil), // 21: example.app.order.v1.OrderSummary
	(*Snapshot)(nil),     // 22: example.app.order.v1.Snapshot
	nil,                  // 23: example.app.order.v1.Order.ItemsEntry
	nil,                  // 24: example.app.order.v1.Order.TagsEntry
}
var file_example_app_order_v1_order_v1_proto_depIdxs = []int32{
	0,  // 0: example.app.order.v1.Order.state:type_name -> example.app.order.v1.State
	23, // 1: example.app.order.v1.Order.items:type_name -> example.app.order.v1.Order.ItemsEntry
	24, // 2: example.app.order.v1.Order.tags:type_name -> example.app.order.v1.Order.TagsEntry
	1,  // 3: example.app.order.v1.OrderList.items:type_name -> example.app.order.v1.Order
	3,  // 4: example.app.order.v1.AddItem.item:type_name -> example.app.order.v1.LineItem
	4,  // 5: example.app.order.v1.AddTag.tag:type_name -> example.app.order.v1.Tag
	3,  // 6: example.app.order.v1.ItemAdded.item:type_name -> example.app.order.v1.LineItem
	4,  // 7: example.app.order.v1.TagAdded.tag:type_name -> example.app.order.v1.Tag
	0,  // 8: example.app.order.v1.OrderSummary.state:type_name -> example.app.order.v1.State
	1,  // 9: example.app.order.v1.Snapshot.snapshot:type_name -> example.app.order.v1.Order
	3,  // 10: example.app.order.v1.Order.ItemsEntry.value:type_name -> example.app.order.v1.LineItem
	4,  // 11: example.app.order.v1.Order.TagsEntry.value:type_name -> example.app.order.v1.Tag
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_example_app_order_v1_order_v1_proto_init() }
func file_example_app_order_v1_order_v1_proto_init() {
	if File_example_app_order_v1_order_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_app_order_v1_order_v1_proto_rawDesc), len(file_example_app_order_v1_order_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_app_order_v1_order_v1_proto_goTypes,
		DependencyIndexes: file_example_app_order_v1_order_v1_proto_depIdxs,
		EnumInfos:         file_example_app_order_v1_order_v1_proto_enumTypes,
		MessageInfos:      file_example_app_order_v1_order_v1_proto_msgTypes,
	}.Build()
	File_example_app_order_v1_order_v1_proto = out.File
	file_example_app_order_v1_order_v1_proto_goTypes = nil
	file_example_app_order_v1_order_v1_proto_depIdxs = nil
}
