// Code generated by protoc-gen-protosource. DO NOT EDIT.

package orderv1

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strings"

	"github.com/funinthecloud/protosource"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// Repo is a package-specific interface for dependency injection.
// It embeds protosource.Repo so that *protosource.Repository satisfies it,
// while giving each aggregate package a distinct type for Wire.
type Repo interface {
	protosource.Repo
}

// Handler provides request handler functions for the Order aggregate.
type Handler struct {
	repo Repo
}

// NewHandler creates a new Handler instance with the given repository.
func NewHandler(repo Repo) *Handler {
	return &Handler{repo: repo}
}

// RegisterRoutes registers all handler routes on the given router.
func (h *Handler) RegisterRoutes(router *protosource.Router) {

	router.Handle("POST", "example/app/order/v1/create", h.HandleCreate)

	router.Handle("POST", "example/app/order/v1/additem", h.HandleAddItem)

	router.Handle("POST", "example/app/order/v1/removeitem", h.HandleRemoveItem)

	router.Handle("POST", "example/app/order/v1/addtag", h.HandleAddTag)

	router.Handle("POST", "example/app/order/v1/removetag", h.HandleRemoveTag)

	router.Handle("POST", "example/app/order/v1/setshipping", h.HandleSetShipping)

	router.Handle("POST", "example/app/order/v1/place", h.HandlePlace)

	router.Handle("POST", "example/app/order/v1/cancel", h.HandleCancel)

	router.Handle("GET", "example/app/order/v1/{id}", h.HandleGet)
	router.Handle("GET", "example/app/order/v1/{id}/history", h.HandleHistory)
}

// HandleCreate processes a Create command.
func (h *Handler) HandleCreate(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &Create{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleAddItem processes a AddItem command.
func (h *Handler) HandleAddItem(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &AddItem{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleRemoveItem processes a RemoveItem command.
func (h *Handler) HandleRemoveItem(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &RemoveItem{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleAddTag processes a AddTag command.
func (h *Handler) HandleAddTag(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &AddTag{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleRemoveTag processes a RemoveTag command.
func (h *Handler) HandleRemoveTag(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &RemoveTag{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleSetShipping processes a SetShipping command.
func (h *Handler) HandleSetShipping(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &SetShipping{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandlePlace processes a Place command.
func (h *Handler) HandlePlace(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &Place{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleCancel processes a Cancel command.
func (h *Handler) HandleCancel(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return protosource.Response{
			StatusCode: http.StatusUnauthorized,
			Body:       `{"error":"unauthorized: no actor identity found"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	cmd := &Cancel{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"invalid request body"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleGet retrieves the current state of a Order aggregate.
func (h *Handler) HandleGet(ctx context.Context, request protosource.Request) protosource.Response {
	id := extractID(request)
	if id == "" {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"missing required parameter: id"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	aggregate, err := h.repo.Load(ctx, id)
	if err != nil {
		if errors.Is(err, protosource.ErrAggregateNotFound) {
			return protosource.Response{
				StatusCode: http.StatusNotFound,
				Body:       `{"error":"aggregate not found"}`,
				Headers:    map[string]string{"Content-Type": "application/json"},
			}
		}
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"internal server error"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	body, contentType, err := marshalResponse(request, aggregate)
	if err != nil {
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"failed to serialize aggregate"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": contentType},
	}
}

// HandleHistory retrieves the full event history for a Order aggregate.
func (h *Handler) HandleHistory(ctx context.Context, request protosource.Request) protosource.Response {
	id := extractID(request)
	if id == "" {
		return protosource.Response{
			StatusCode: http.StatusBadRequest,
			Body:       `{"error":"missing required parameter: id"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	history, err := h.repo.History(ctx, id)
	if err != nil {
		if errors.Is(err, protosource.ErrAggregateNotFound) {
			return protosource.Response{
				StatusCode: http.StatusNotFound,
				Body:       `{"error":"aggregate not found"}`,
				Headers:    map[string]string{"Content-Type": "application/json"},
			}
		}
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"internal server error"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	body, contentType, err := marshalResponse(request, history)
	if err != nil {
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"failed to serialize history"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": contentType},
	}
}

// acceptsProtobuf checks the Accept header: protobuf wins if present,
// then JSON if present, otherwise defaults to protobuf.
func acceptsProtobuf(request protosource.Request) bool {
	accept := request.Headers["Accept"]
	if accept == "" {
		accept = request.Headers["accept"]
	}
	if strings.Contains(accept, "application/protobuf") {
		return true
	}
	if strings.Contains(accept, "application/json") {
		return false
	}
	return true
}

// isProtobufContent checks the Content-Type header: protobuf wins if present,
// then JSON if present, otherwise defaults to protobuf.
func isProtobufContent(request protosource.Request) bool {
	ct := request.Headers["Content-Type"]
	if ct == "" {
		ct = request.Headers["content-type"]
	}
	if strings.Contains(ct, "application/protobuf") {
		return true
	}
	if strings.Contains(ct, "application/json") {
		return false
	}
	return true
}

// unmarshalCommand decodes the request body into a proto message, using
// Content-Type to select protobuf binary or JSON deserialization.
func unmarshalCommand(request protosource.Request, msg proto.Message) error {
	if isProtobufContent(request) {
		return proto.Unmarshal([]byte(request.Body), msg)
	}
	return protojson.Unmarshal([]byte(request.Body), msg)
}

// marshalResponse encodes a proto message for the response, using the Accept
// header to select protobuf binary or JSON serialization. Returns the
// serialized bytes and the appropriate Content-Type.
func marshalResponse(request protosource.Request, msg proto.Message) ([]byte, string, error) {
	if acceptsProtobuf(request) {
		b, err := proto.Marshal(msg)
		return b, "application/protobuf", err
	}
	b, err := protojson.Marshal(msg)
	return b, "application/json", err
}

// extractID extracts the aggregate ID from path parameters or query string.
func extractID(request protosource.Request) string {
	if id, ok := request.PathParameters["id"]; ok && id != "" {
		return id
	}
	return request.QueryParameters["id"]
}

// jsonResponse marshals a value as JSON and returns a protosource.Response.
func jsonResponse(statusCode int, v any) protosource.Response {
	b, err := json.Marshal(v)
	if err != nil {
		return protosource.Response{
			StatusCode: http.StatusInternalServerError,
			Body:       `{"error":"failed to serialize response"}`,
			Headers:    map[string]string{"Content-Type": "application/json"},
		}
	}
	return protosource.Response{
		StatusCode: statusCode,
		Body:       string(b),
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// commandErrorResponse maps protosource errors to appropriate HTTP responses.
func commandErrorResponse(err error) protosource.Response {
	statusCode := http.StatusInternalServerError
	message := "internal server error"

	switch {
	case errors.Is(err, protosource.ErrValidationFailed):
		statusCode = http.StatusBadRequest
		message = err.Error()
	case errors.Is(err, protosource.ErrEmptyAggregateId):
		statusCode = http.StatusBadRequest
		message = "aggregate id is required"
	case errors.Is(err, protosource.ErrAlreadyCreated):
		statusCode = http.StatusConflict
		message = "aggregate already exists"
	case errors.Is(err, protosource.ErrNotCreatedYet):
		statusCode = http.StatusNotFound
		message = "aggregate not found"
	case errors.Is(err, protosource.ErrAggregateNotFound):
		statusCode = http.StatusNotFound
		message = "aggregate not found"
	case errors.Is(err, protosource.ErrUnauthorized):
		statusCode = http.StatusForbidden
		message = "command not authorized"
	}

	return jsonResponse(statusCode, map[string]string{"error": message})
}
