// Code generated by protoc-gen-protosource. DO NOT EDIT.

package orderv1

import (
	"github.com/funinthecloud/protosource"
	"github.com/goforj/wire"
)

// Repository wraps *protosource.Repository for the Order aggregate,
// giving Wire a distinct concrete type per aggregate.
type Repository struct{ *protosource.Repository }

// ProvideRepository creates a Order repository accepting interfaces.
func ProvideRepository(store protosource.Store, serializer protosource.Serializer) *Repository {
	return &Repository{NewRepository(store, serializer)}
}

// ProviderSet provides the Order repository and binds it to Repo.
var ProviderSet = wire.NewSet(
	ProvideRepository,
	wire.Bind(new(Repo), new(*Repository)),
)
