// Code generated by protoc-gen-protosource. DO NOT EDIT.

package orderv1

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	historyv1 "github.com/funinthecloud/protosource/history/v1"
	"github.com/funinthecloud/protosource/httpclient"
	"google.golang.org/protobuf/encoding/protojson"
)

const routePath = "example/app/order/v1"

// HTTPClient is a typed HTTP client for the Order aggregate.
type HTTPClient struct {
	c httpclient.Doer
}

// NewHTTPClient creates a new Order HTTP client.
// Accepts httpclient.Doer for testability — use *httpclient.Client in
// production and a mock in tests.
func NewHTTPClient(c httpclient.Doer) *HTTPClient {
	return &HTTPClient{c: c}
}

// Create sends the Create command.
func (c *HTTPClient) Create(ctx context.Context, id string, customerId string, customerName string) (*httpclient.ApplyResult, error) {
	cmd := &Create{
		Id:           id,
		CustomerId:   customerId,
		CustomerName: customerName,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// AddItem sends the AddItem command.
func (c *HTTPClient) AddItem(ctx context.Context, id string, item *LineItem) (*httpclient.ApplyResult, error) {
	cmd := &AddItem{
		Id:   id,
		Item: item,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// RemoveItem sends the RemoveItem command.
func (c *HTTPClient) RemoveItem(ctx context.Context, id string, itemId string) (*httpclient.ApplyResult, error) {
	cmd := &RemoveItem{
		Id:     id,
		ItemId: itemId,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// AddTag sends the AddTag command.
func (c *HTTPClient) AddTag(ctx context.Context, id string, tag *Tag) (*httpclient.ApplyResult, error) {
	cmd := &AddTag{
		Id:  id,
		Tag: tag,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// RemoveTag sends the RemoveTag command.
func (c *HTTPClient) RemoveTag(ctx context.Context, id string, key string) (*httpclient.ApplyResult, error) {
	cmd := &RemoveTag{
		Id:  id,
		Key: key,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// SetShipping sends the SetShipping command.
func (c *HTTPClient) SetShipping(ctx context.Context, id string, shippingAddress string) (*httpclient.ApplyResult, error) {
	cmd := &SetShipping{
		Id:              id,
		ShippingAddress: shippingAddress,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Place sends the Place command.
func (c *HTTPClient) Place(ctx context.Context, id string, placedAt int64) (*httpclient.ApplyResult, error) {
	cmd := &Place{
		Id:       id,
		PlacedAt: placedAt,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Cancel sends the Cancel command.
func (c *HTTPClient) Cancel(ctx context.Context, id string, reason string) (*httpclient.ApplyResult, error) {
	cmd := &Cancel{
		Id:     id,
		Reason: reason,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Load retrieves the current state of the Order aggregate.
func (c *HTTPClient) Load(ctx context.Context, id string) (*Order, error) {
	agg := &Order{}
	if err := c.c.Load(ctx, routePath, id, agg); err != nil {
		return nil, err
	}
	return agg, nil
}

// History retrieves the full event history for the Order aggregate.
func (c *HTTPClient) History(ctx context.Context, id string) (*historyv1.History, error) {
	return c.c.History(ctx, routePath, id)
}

// QueryByCustomerId queries by customer_id via GSI1.
func (c *HTTPClient) QueryByCustomerId(ctx context.Context, customerId string) ([]*Order, error) {
	params := map[string]string{
		"customer_id": customerId,
	}
	return unmarshalQueryResultsOrder(c.c.Query(ctx, routePath, "by-customer-id", params))
}

// QueryByCustomerIdWithCreateAt queries by customer_id with a sort key condition via GSI1.
func (c *HTTPClient) QueryByCustomerIdWithCreateAt(ctx context.Context, customerId string, skOp string, createAt int64) ([]*Order, error) {
	params := map[string]string{
		"customer_id": customerId,
		"sk_op":       skOp,
		"create_at":   strconv.FormatInt(createAt, 10),
	}
	return unmarshalQueryResultsOrder(c.c.Query(ctx, routePath, "by-customer-id", params))
}

// Ensure strconv is used (suppresses unused import when no numeric GSI fields exist).
var _ = strconv.FormatInt

func unmarshalQueryResultsOrder(raw []json.RawMessage, err error) ([]*Order, error) {
	if err != nil {
		return nil, err
	}
	results := make([]*Order, 0, len(raw))
	for _, item := range raw {
		agg := &Order{}
		if err := protojson.Unmarshal(item, agg); err != nil {
			return nil, fmt.Errorf("unmarshal query result: %w", err)
		}
		results = append(results, agg)
	}
	return results, nil
}
