// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: funinthecloud/protosource/record/v1/record_v1.proto

package recordv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_funinthecloud_protosource_record_v1_record_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_record_v1_record_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_record_v1_record_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_funinthecloud_protosource_record_v1_record_v1_proto protoreflect.FileDescriptor

const file_funinthecloud_protosource_record_v1_record_v1_proto_rawDesc = "" +
	"\n" +
	"3funinthecloud/protosource/record/v1/record_v1.proto\x12#funinthecloud.protosource.record.v1\"6\n" +
	"\x06Record\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04dataB\xa0\x02\n" +
	"'com.funinthecloud.protosource.record.v1B\rRecordV1ProtoP\x01Z7github.com/funinthecloud/protosource/record/v1;recordv1\xa2\x02\x03FPR\xaa\x02#Funinthecloud.Protosource.Record.V1\xca\x02#Funinthecloud\\Protosource\\Record\\V1\xe2\x02/Funinthecloud\\Protosource\\Record\\V1\\GPBMetadata\xea\x02&Funinthecloud::Protosource::Record::V1b\x06proto3"

var (
	file_funinthecloud_protosource_record_v1_record_v1_proto_rawDescOnce sync.Once
	file_funinthecloud_protosource_record_v1_record_v1_proto_rawDescData []byte
)

func file_funinthecloud_protosource_record_v1_record_v1_proto_rawDescGZIP() []byte {
	file_funinthecloud_protosource_record_v1_record_v1_proto_rawDescOnce.Do(func() {
		file_funinthecloud_protosource_record_v1_record_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_record_v1_record_v1_proto_rawDesc), len(file_funinthecloud_protosource_record_v1_record_v1_proto_rawDesc)))
	})
	return file_funinthecloud_protosource_record_v1_record_v1_proto_rawDescData
}

var file_funinthecloud_protosource_record_v1_record_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_funinthecloud_protosource_record_v1_record_v1_proto_goTypes = []any{
	(*Record)(nil), // 0: funinthecloud.protosource.record.v1.Record
}
var file_funinthecloud_protosource_record_v1_record_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_funinthecloud_protosource_record_v1_record_v1_proto_init() }
func file_funinthecloud_protosource_record_v1_record_v1_proto_init() {
	if File_funinthecloud_protosource_record_v1_record_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_record_v1_record_v1_proto_rawDesc), len(file_funinthecloud_protosource_record_v1_record_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_funinthecloud_protosource_record_v1_record_v1_proto_goTypes,
		DependencyIndexes: file_funinthecloud_protosource_record_v1_record_v1_proto_depIdxs,
		MessageInfos:      file_funinthecloud_protosource_record_v1_record_v1_proto_msgTypes,
	}.Build()
	File_funinthecloud_protosource_record_v1_record_v1_proto = out.File
	file_funinthecloud_protosource_record_v1_record_v1_proto_goTypes = nil
	file_funinthecloud_protosource_record_v1_record_v1_proto_depIdxs = nil
}
