
// Code generated by protoc-gen-protosource-ts. DO NOT EDIT.

import type { ProtosourceClient, CommandResponse, History } from "@protosource/client";
import { CreateSchema, UpdateSchema, SampleSchema, SampleListSchema } from "./samplenosnapshot_v1_pb.js";
import type { Create, Update, Sample, SampleList } from "./samplenosnapshot_v1_pb.js";

const routePath = "example/app/samplenosnapshot/v1";

export class SampleHTTPClient {
  private readonly client: ProtosourceClient;

  constructor(client: ProtosourceClient) {
    this.client = client;
  }

  async create(id: string, body: string): Promise<CommandResponse> {
    return this.client.apply(routePath, CreateSchema, { id, body });
  }

  async update(id: string, body: string): Promise<CommandResponse> {
    return this.client.apply(routePath, UpdateSchema, { id, body });
  }

  async load(id: string): Promise<Sample> {
    return this.client.load(routePath, id, SampleSchema);
  }

  async get(id: string): Promise<Sample> {
    return this.client.get(routePath, id, SampleSchema);
  }

  async history(id: string): Promise<History> {
    return this.client.history(routePath, id);
  }

}
