// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: funinthecloud/protosource/options/v1/options_v1.proto

package optionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandLifecycle describes when a command is valid relative to the aggregate's
// existence. UNSPECIFIED skips version validation entirely, giving authors full
// control. CREATION requires the aggregate to be new (version == 0). MUTATION
// requires the aggregate to already exist (version > 0).
type CommandLifecycle int32

const (
	CommandLifecycle_COMMAND_LIFECYCLE_UNSPECIFIED CommandLifecycle = 0
	CommandLifecycle_COMMAND_LIFECYCLE_CREATION    CommandLifecycle = 1
	CommandLifecycle_COMMAND_LIFECYCLE_MUTATION    CommandLifecycle = 2
)

// Enum value maps for CommandLifecycle.
var (
	CommandLifecycle_name = map[int32]string{
		0: "COMMAND_LIFECYCLE_UNSPECIFIED",
		1: "COMMAND_LIFECYCLE_CREATION",
		2: "COMMAND_LIFECYCLE_MUTATION",
	}
	CommandLifecycle_value = map[string]int32{
		"COMMAND_LIFECYCLE_UNSPECIFIED": 0,
		"COMMAND_LIFECYCLE_CREATION":    1,
		"COMMAND_LIFECYCLE_MUTATION":    2,
	}
)

func (x CommandLifecycle) Enum() *CommandLifecycle {
	p := new(CommandLifecycle)
	*p = x
	return p
}

func (x CommandLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_enumTypes[0].Descriptor()
}

func (CommandLifecycle) Type() protoreflect.EnumType {
	return &file_funinthecloud_protosource_options_v1_options_v1_proto_enumTypes[0]
}

func (x CommandLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandLifecycle.Descriptor instead.
func (CommandLifecycle) EnumDescriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP(), []int{0}
}

type FileOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Role:
	//
	//	*MessageOptions_Command
	//	*MessageOptions_Event
	//	*MessageOptions_Aggregate
	//	*MessageOptions_Projection
	//	*MessageOptions_Snapshot
	Role          isMessageOptions_Role `protobuf_oneof:"role"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOptions) GetRole() isMessageOptions_Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *MessageOptions) GetCommand() *CommandOptions {
	if x != nil {
		if x, ok := x.Role.(*MessageOptions_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *MessageOptions) GetEvent() *EventOptions {
	if x != nil {
		if x, ok := x.Role.(*MessageOptions_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *MessageOptions) GetAggregate() *AggregateOptions {
	if x != nil {
		if x, ok := x.Role.(*MessageOptions_Aggregate); ok {
			return x.Aggregate
		}
	}
	return nil
}

func (x *MessageOptions) GetProjection() *ProjectionOptions {
	if x != nil {
		if x, ok := x.Role.(*MessageOptions_Projection); ok {
			return x.Projection
		}
	}
	return nil
}

func (x *MessageOptions) GetSnapshot() *SnapshotOptions {
	if x != nil {
		if x, ok := x.Role.(*MessageOptions_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isMessageOptions_Role interface {
	isMessageOptions_Role()
}

type MessageOptions_Command struct {
	Command *CommandOptions `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type MessageOptions_Event struct {
	Event *EventOptions `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type MessageOptions_Aggregate struct {
	Aggregate *AggregateOptions `protobuf:"bytes,3,opt,name=aggregate,proto3,oneof"`
}

type MessageOptions_Projection struct {
	Projection *ProjectionOptions `protobuf:"bytes,4,opt,name=projection,proto3,oneof"`
}

type MessageOptions_Snapshot struct {
	Snapshot *SnapshotOptions `protobuf:"bytes,5,opt,name=snapshot,proto3,oneof"`
}

func (*MessageOptions_Command) isMessageOptions_Role() {}

func (*MessageOptions_Event) isMessageOptions_Role() {}

func (*MessageOptions_Aggregate) isMessageOptions_Role() {}

func (*MessageOptions_Projection) isMessageOptions_Role() {}

func (*MessageOptions_Snapshot) isMessageOptions_Role() {}

type CommandOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event message names this command produces upon successful execution.
	// Typically one. Two is uncommon but valid.
	// More than two is a signal the command is doing too much.
	ProducesEvents []string `protobuf:"bytes,1,rep,name=produces_events,json=producesEvents,proto3" json:"produces_events,omitempty"`
	// When this command is valid relative to the aggregate's lifecycle.
	// UNSPECIFIED (default) skips version validation.
	// CREATION requires version == 0 (new aggregate).
	// MUTATION requires version > 0 (existing aggregate).
	Lifecycle CommandLifecycle `protobuf:"varint,2,opt,name=lifecycle,proto3,enum=funinthecloud.protosource.options.v1.CommandLifecycle" json:"lifecycle,omitempty"`
	// The aggregate states in which this command is allowed. When specified,
	// the plugin generates an Authorize(aggregate) method that rejects the
	// command if the aggregate's current state is not in this list.
	//
	// Values must be valid enum value names defined in the same proto file.
	// The plugin validates this at generation time.
	//
	// When empty (default), no Authorize method is generated — the command
	// is allowed in any state. Hand-written Authorize methods can still be
	// used for complex authorization logic.
	AllowedStates []string `protobuf:"bytes,3,rep,name=allowed_states,json=allowedStates,proto3" json:"allowed_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOptions) Reset() {
	*x = CommandOptions{}
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOptions) ProtoMessage() {}

func (x *CommandOptions) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOptions.ProtoReflect.Descriptor instead.
func (*CommandOptions) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP(), []int{2}
}

func (x *CommandOptions) GetProducesEvents() []string {
	if x != nil {
		return x.ProducesEvents
	}
	return nil
}

func (x *CommandOptions) GetLifecycle() CommandLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return CommandLifecycle_COMMAND_LIFECYCLE_UNSPECIFIED
}

func (x *CommandOptions) GetAllowedStates() []string {
	if x != nil {
		return x.AllowedStates
	}
	return nil
}

type EventOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The aggregate type that owns this event's stream. e.g. "Order"
	AggregateType string `protobuf:"bytes,1,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	// If set, the generated On method will assign this state enum value to the
	// aggregate's State field when this event is applied. Use the full enum value
	// name, e.g. "STATE_LOCKED". The plugin validates that the value exists in
	// the same proto file at generation time.
	SetsState     string `protobuf:"bytes,2,opt,name=sets_state,json=setsState,proto3" json:"sets_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOptions.ProtoReflect.Descriptor instead.
func (*EventOptions) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP(), []int{3}
}

func (x *EventOptions) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *EventOptions) GetSetsState() string {
	if x != nil {
		return x.SetsState
	}
	return ""
}

type AggregateOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix for the event stream ID. e.g. "order-" → stream ID = "order-{id}"
	StreamPrefix  string `protobuf:"bytes,1,opt,name=stream_prefix,json=streamPrefix,proto3" json:"stream_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateOptions) Reset() {
	*x = AggregateOptions{}
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateOptions) ProtoMessage() {}

func (x *AggregateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateOptions.ProtoReflect.Descriptor instead.
func (*AggregateOptions) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP(), []int{4}
}

func (x *AggregateOptions) GetStreamPrefix() string {
	if x != nil {
		return x.StreamPrefix
	}
	return ""
}

type ProjectionOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The aggregate types this projection subscribes to.
	SourceAggregates []string `protobuf:"bytes,1,rep,name=source_aggregates,json=sourceAggregates,proto3" json:"source_aggregates,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProjectionOptions) Reset() {
	*x = ProjectionOptions{}
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionOptions) ProtoMessage() {}

func (x *ProjectionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionOptions.ProtoReflect.Descriptor instead.
func (*ProjectionOptions) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectionOptions) GetSourceAggregates() []string {
	if x != nil {
		return x.SourceAggregates
	}
	return nil
}

type SnapshotOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How frequently to write a snapshot, and the exact lookback window on
	// replay. 0 = defer to runtime default.
	EveryNEvents uint32 `protobuf:"varint,1,opt,name=every_n_events,json=everyNEvents,proto3" json:"every_n_events,omitempty"`
	// Explicit opt-out for low-velocity aggregates where replay is always cheap.
	// Prefer this over omitting the annotation entirely — intent is explicit.
	Disabled      bool `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotOptions) Reset() {
	*x = SnapshotOptions{}
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotOptions) ProtoMessage() {}

func (x *SnapshotOptions) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotOptions.ProtoReflect.Descriptor instead.
func (*SnapshotOptions) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotOptions) GetEveryNEvents() uint32 {
	if x != nil {
		return x.EveryNEvents
	}
	return 0
}

func (x *SnapshotOptions) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

var file_funinthecloud_protosource_options_v1_options_v1_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         60106,
		Name:          "funinthecloud.protosource.options.v1.protosource_file",
		Tag:           "bytes,60106,opt,name=protosource_file",
		Filename:      "funinthecloud/protosource/options/v1/options_v1.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         60105,
		Name:          "funinthecloud.protosource.options.v1.protosource_message_type",
		Tag:           "bytes,60105,opt,name=protosource_message_type",
		Filename:      "funinthecloud/protosource/options/v1/options_v1.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional funinthecloud.protosource.options.v1.FileOptions protosource_file = 60106;
	E_ProtosourceFile = &file_funinthecloud_protosource_options_v1_options_v1_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional funinthecloud.protosource.options.v1.MessageOptions protosource_message_type = 60105;
	E_ProtosourceMessageType = &file_funinthecloud_protosource_options_v1_options_v1_proto_extTypes[1]
)

var File_funinthecloud_protosource_options_v1_options_v1_proto protoreflect.FileDescriptor

const file_funinthecloud_protosource_options_v1_options_v1_proto_rawDesc = "" +
	"\n" +
	"5funinthecloud/protosource/options/v1/options_v1.proto\x12$funinthecloud.protosource.options.v1\x1a google/protobuf/descriptor.proto\"'\n" +
	"\vFileOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\xbe\x03\n" +
	"\x0eMessageOptions\x12P\n" +
	"\acommand\x18\x01 \x01(\v24.funinthecloud.protosource.options.v1.CommandOptionsH\x00R\acommand\x12J\n" +
	"\x05event\x18\x02 \x01(\v22.funinthecloud.protosource.options.v1.EventOptionsH\x00R\x05event\x12V\n" +
	"\taggregate\x18\x03 \x01(\v26.funinthecloud.protosource.options.v1.AggregateOptionsH\x00R\taggregate\x12Y\n" +
	"\n" +
	"projection\x18\x04 \x01(\v27.funinthecloud.protosource.options.v1.ProjectionOptionsH\x00R\n" +
	"projection\x12S\n" +
	"\bsnapshot\x18\x05 \x01(\v25.funinthecloud.protosource.options.v1.SnapshotOptionsH\x00R\bsnapshotB\x06\n" +
	"\x04role\"\xb6\x01\n" +
	"\x0eCommandOptions\x12'\n" +
	"\x0fproduces_events\x18\x01 \x03(\tR\x0eproducesEvents\x12T\n" +
	"\tlifecycle\x18\x02 \x01(\x0e26.funinthecloud.protosource.options.v1.CommandLifecycleR\tlifecycle\x12%\n" +
	"\x0eallowed_states\x18\x03 \x03(\tR\rallowedStates\"T\n" +
	"\fEventOptions\x12%\n" +
	"\x0eaggregate_type\x18\x01 \x01(\tR\raggregateType\x12\x1d\n" +
	"\n" +
	"sets_state\x18\x02 \x01(\tR\tsetsState\"7\n" +
	"\x10AggregateOptions\x12#\n" +
	"\rstream_prefix\x18\x01 \x01(\tR\fstreamPrefix\"@\n" +
	"\x11ProjectionOptions\x12+\n" +
	"\x11source_aggregates\x18\x01 \x03(\tR\x10sourceAggregates\"S\n" +
	"\x0fSnapshotOptions\x12$\n" +
	"\x0eevery_n_events\x18\x01 \x01(\rR\feveryNEvents\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled*u\n" +
	"\x10CommandLifecycle\x12!\n" +
	"\x1dCOMMAND_LIFECYCLE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOMMAND_LIFECYCLE_CREATION\x10\x01\x12\x1e\n" +
	"\x1aCOMMAND_LIFECYCLE_MUTATION\x10\x02:|\n" +
	"\x10protosource_file\x12\x1c.google.protobuf.FileOptions\x18\xca\xd5\x03 \x01(\v21.funinthecloud.protosource.options.v1.FileOptionsR\x0fprotosourceFile:\x91\x01\n" +
	"\x18protosource_message_type\x12\x1f.google.protobuf.MessageOptions\x18\xc9\xd5\x03 \x01(\v24.funinthecloud.protosource.options.v1.MessageOptionsR\x16protosourceMessageTypeB\xa8\x02\n" +
	"(com.funinthecloud.protosource.options.v1B\x0eOptionsV1ProtoP\x01Z9github.com/funinthecloud/protosource/options/v1;optionsv1\xa2\x02\x03FPO\xaa\x02$Funinthecloud.Protosource.Options.V1\xca\x02$Funinthecloud\\Protosource\\Options\\V1\xe2\x020Funinthecloud\\Protosource\\Options\\V1\\GPBMetadata\xea\x02'Funinthecloud::Protosource::Options::V1b\x06proto3"

var (
	file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescOnce sync.Once
	file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescData []byte
)

func file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescGZIP() []byte {
	file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescOnce.Do(func() {
		file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_options_v1_options_v1_proto_rawDesc), len(file_funinthecloud_protosource_options_v1_options_v1_proto_rawDesc)))
	})
	return file_funinthecloud_protosource_options_v1_options_v1_proto_rawDescData
}

var file_funinthecloud_protosource_options_v1_options_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_funinthecloud_protosource_options_v1_options_v1_proto_goTypes = []any{
	(CommandLifecycle)(0),               // 0: funinthecloud.protosource.options.v1.CommandLifecycle
	(*FileOptions)(nil),                 // 1: funinthecloud.protosource.options.v1.FileOptions
	(*MessageOptions)(nil),              // 2: funinthecloud.protosource.options.v1.MessageOptions
	(*CommandOptions)(nil),              // 3: funinthecloud.protosource.options.v1.CommandOptions
	(*EventOptions)(nil),                // 4: funinthecloud.protosource.options.v1.EventOptions
	(*AggregateOptions)(nil),            // 5: funinthecloud.protosource.options.v1.AggregateOptions
	(*ProjectionOptions)(nil),           // 6: funinthecloud.protosource.options.v1.ProjectionOptions
	(*SnapshotOptions)(nil),             // 7: funinthecloud.protosource.options.v1.SnapshotOptions
	(*descriptorpb.FileOptions)(nil),    // 8: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
}
var file_funinthecloud_protosource_options_v1_options_v1_proto_depIdxs = []int32{
	3,  // 0: funinthecloud.protosource.options.v1.MessageOptions.command:type_name -> funinthecloud.protosource.options.v1.CommandOptions
	4,  // 1: funinthecloud.protosource.options.v1.MessageOptions.event:type_name -> funinthecloud.protosource.options.v1.EventOptions
	5,  // 2: funinthecloud.protosource.options.v1.MessageOptions.aggregate:type_name -> funinthecloud.protosource.options.v1.AggregateOptions
	6,  // 3: funinthecloud.protosource.options.v1.MessageOptions.projection:type_name -> funinthecloud.protosource.options.v1.ProjectionOptions
	7,  // 4: funinthecloud.protosource.options.v1.MessageOptions.snapshot:type_name -> funinthecloud.protosource.options.v1.SnapshotOptions
	0,  // 5: funinthecloud.protosource.options.v1.CommandOptions.lifecycle:type_name -> funinthecloud.protosource.options.v1.CommandLifecycle
	8,  // 6: funinthecloud.protosource.options.v1.protosource_file:extendee -> google.protobuf.FileOptions
	9,  // 7: funinthecloud.protosource.options.v1.protosource_message_type:extendee -> google.protobuf.MessageOptions
	1,  // 8: funinthecloud.protosource.options.v1.protosource_file:type_name -> funinthecloud.protosource.options.v1.FileOptions
	2,  // 9: funinthecloud.protosource.options.v1.protosource_message_type:type_name -> funinthecloud.protosource.options.v1.MessageOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	8,  // [8:10] is the sub-list for extension type_name
	6,  // [6:8] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_funinthecloud_protosource_options_v1_options_v1_proto_init() }
func file_funinthecloud_protosource_options_v1_options_v1_proto_init() {
	if File_funinthecloud_protosource_options_v1_options_v1_proto != nil {
		return
	}
	file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes[1].OneofWrappers = []any{
		(*MessageOptions_Command)(nil),
		(*MessageOptions_Event)(nil),
		(*MessageOptions_Aggregate)(nil),
		(*MessageOptions_Projection)(nil),
		(*MessageOptions_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_options_v1_options_v1_proto_rawDesc), len(file_funinthecloud_protosource_options_v1_options_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_funinthecloud_protosource_options_v1_options_v1_proto_goTypes,
		DependencyIndexes: file_funinthecloud_protosource_options_v1_options_v1_proto_depIdxs,
		EnumInfos:         file_funinthecloud_protosource_options_v1_options_v1_proto_enumTypes,
		MessageInfos:      file_funinthecloud_protosource_options_v1_options_v1_proto_msgTypes,
		ExtensionInfos:    file_funinthecloud_protosource_options_v1_options_v1_proto_extTypes,
	}.Build()
	File_funinthecloud_protosource_options_v1_options_v1_proto = out.File
	file_funinthecloud_protosource_options_v1_options_v1_proto_goTypes = nil
	file_funinthecloud_protosource_options_v1_options_v1_proto_depIdxs = nil
}
