// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: funinthecloud/protosource/history/v1/history_v1.proto

package historyv1

import (
	v1 "github.com/funinthecloud/protosource/record/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type History struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*v1.Record           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_funinthecloud_protosource_history_v1_history_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_funinthecloud_protosource_history_v1_history_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_funinthecloud_protosource_history_v1_history_v1_proto_rawDescGZIP(), []int{0}
}

func (x *History) GetRecords() []*v1.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_funinthecloud_protosource_history_v1_history_v1_proto protoreflect.FileDescriptor

const file_funinthecloud_protosource_history_v1_history_v1_proto_rawDesc = "" +
	"\n" +
	"5funinthecloud/protosource/history/v1/history_v1.proto\x12$funinthecloud.protosource.history.v1\x1a3funinthecloud/protosource/record/v1/record_v1.proto\"P\n" +
	"\aHistory\x12E\n" +
	"\arecords\x18\x01 \x03(\v2+.funinthecloud.protosource.record.v1.RecordR\arecordsB\xa8\x02\n" +
	"(com.funinthecloud.protosource.history.v1B\x0eHistoryV1ProtoP\x01Z9github.com/funinthecloud/protosource/history/v1;historyv1\xa2\x02\x03FPH\xaa\x02$Funinthecloud.Protosource.History.V1\xca\x02$Funinthecloud\\Protosource\\History\\V1\xe2\x020Funinthecloud\\Protosource\\History\\V1\\GPBMetadata\xea\x02'Funinthecloud::Protosource::History::V1b\x06proto3"

var (
	file_funinthecloud_protosource_history_v1_history_v1_proto_rawDescOnce sync.Once
	file_funinthecloud_protosource_history_v1_history_v1_proto_rawDescData []byte
)

func file_funinthecloud_protosource_history_v1_history_v1_proto_rawDescGZIP() []byte {
	file_funinthecloud_protosource_history_v1_history_v1_proto_rawDescOnce.Do(func() {
		file_funinthecloud_protosource_history_v1_history_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_history_v1_history_v1_proto_rawDesc), len(file_funinthecloud_protosource_history_v1_history_v1_proto_rawDesc)))
	})
	return file_funinthecloud_protosource_history_v1_history_v1_proto_rawDescData
}

var file_funinthecloud_protosource_history_v1_history_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_funinthecloud_protosource_history_v1_history_v1_proto_goTypes = []any{
	(*History)(nil),   // 0: funinthecloud.protosource.history.v1.History
	(*v1.Record)(nil), // 1: funinthecloud.protosource.record.v1.Record
}
var file_funinthecloud_protosource_history_v1_history_v1_proto_depIdxs = []int32{
	1, // 0: funinthecloud.protosource.history.v1.History.records:type_name -> funinthecloud.protosource.record.v1.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_funinthecloud_protosource_history_v1_history_v1_proto_init() }
func file_funinthecloud_protosource_history_v1_history_v1_proto_init() {
	if File_funinthecloud_protosource_history_v1_history_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_funinthecloud_protosource_history_v1_history_v1_proto_rawDesc), len(file_funinthecloud_protosource_history_v1_history_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_funinthecloud_protosource_history_v1_history_v1_proto_goTypes,
		DependencyIndexes: file_funinthecloud_protosource_history_v1_history_v1_proto_depIdxs,
		MessageInfos:      file_funinthecloud_protosource_history_v1_history_v1_proto_msgTypes,
	}.Build()
	File_funinthecloud_protosource_history_v1_history_v1_proto = out.File
	file_funinthecloud_protosource_history_v1_history_v1_proto_goTypes = nil
	file_funinthecloud_protosource_history_v1_history_v1_proto_depIdxs = nil
}
