// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: example/app/samplenosnapshot/v1/samplenosnapshot_v1.proto

package samplenoprefixv1

import (
	_ "github.com/funinthecloud/protosource/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sample is the aggregate.
//
//	It must be defined first in the proto,
//	its name must match the first part of the package.
type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	CreateAt      int64                  `protobuf:"varint,3,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	CreateBy      string                 `protobuf:"bytes,4,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	ModifyAt      int64                  `protobuf:"varint,5,opt,name=modify_at,json=modifyAt,proto3" json:"modify_at,omitempty"`
	ModifyBy      string                 `protobuf:"bytes,6,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Sample) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sample) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Sample) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Sample) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *Sample) GetModifyAt() int64 {
	if x != nil {
		return x.ModifyAt
	}
	return 0
}

func (x *Sample) GetModifyBy() string {
	if x != nil {
		return x.ModifyBy
	}
	return ""
}

func (x *Sample) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SampleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Sample              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleList) Reset() {
	*x = SampleList{}
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleList) ProtoMessage() {}

func (x *SampleList) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleList.ProtoReflect.Descriptor instead.
func (*SampleList) Descriptor() ([]byte, []int) {
	return file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescGZIP(), []int{1}
}

func (x *SampleList) GetItems() []*Sample {
	if x != nil {
		return x.Items
	}
	return nil
}

// Create is the command that is used to create a sample.
type Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Create) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Create) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Create) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Update is the command that is used to update a sample.
type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescGZIP(), []int{3}
}

func (x *Update) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Update) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Update) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Created is the event emitted when we create a sample.
type Created struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Created) Reset() {
	*x = Created{}
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Created) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Created) ProtoMessage() {}

func (x *Created) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Created.ProtoReflect.Descriptor instead.
func (*Created) Descriptor() ([]byte, []int) {
	return file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescGZIP(), []int{4}
}

func (x *Created) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Created) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Created) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Created) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Created) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Updated is the event emitted when we update a sample.
type Updated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	At            int64                  `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Updated) Reset() {
	*x = Updated{}
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Updated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updated) ProtoMessage() {}

func (x *Updated) ProtoReflect() protoreflect.Message {
	mi := &file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updated.ProtoReflect.Descriptor instead.
func (*Updated) Descriptor() ([]byte, []int) {
	return file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescGZIP(), []int{5}
}

func (x *Updated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Updated) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Updated) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Updated) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Updated) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto protoreflect.FileDescriptor

const file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDesc = "" +
	"\n" +
	"9example/app/samplenosnapshot/v1/samplenosnapshot_v1.proto\x12\x1fexample.app.samplenosnapshot.v1\x1a5funinthecloud/protosource/options/v1/options_v1.proto\"\xc1\x01\n" +
	"\x06Sample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1b\n" +
	"\tcreate_at\x18\x03 \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tcreate_by\x18\x04 \x01(\tR\bcreateBy\x12\x1b\n" +
	"\tmodify_at\x18\x05 \x01(\x03R\bmodifyAt\x12\x1b\n" +
	"\tmodify_by\x18\x06 \x01(\tR\bmodifyBy\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body:\x05\xb2P\x02\x1a\x00\"K\n" +
	"\n" +
	"SampleList\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.example.app.samplenosnapshot.v1.SampleR\x05items\"T\n" +
	"\x06Create\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body:\x10\xb2P\r\n" +
	"\v\n" +
	"\aCreated\x10\x01\"T\n" +
	"\x06Update\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body:\x10\xb2P\r\n" +
	"\v\n" +
	"\aUpdated\x10\x02\"t\n" +
	"\aCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body:\x05\xb2P\x02\x12\x00\"t\n" +
	"\aUpdated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02at\x18\x03 \x01(\x03R\x02at\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body:\x05\xb2P\x02\x12\x00B\xb9\x02\xbaP\x02\b\x01\n" +
	"#com.example.app.samplenosnapshot.v1B\x17SamplenosnapshotV1ProtoP\x01ZUgithub.com/funinthecloud/protosource/example/app/samplenosnapshot/v1;samplenoprefixv1\xa2\x02\x03EAS\xaa\x02\x1fExample.App.Samplenosnapshot.V1\xca\x02\x1fExample\\App\\Samplenosnapshot\\V1\xe2\x02+Example\\App\\Samplenosnapshot\\V1\\GPBMetadata\xea\x02\"Example::App::Samplenosnapshot::V1b\x06proto3"

var (
	file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescOnce sync.Once
	file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescData []byte
)

func file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescGZIP() []byte {
	file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescOnce.Do(func() {
		file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDesc), len(file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDesc)))
	})
	return file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDescData
}

var file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_goTypes = []any{
	(*Sample)(nil),     // 0: example.app.samplenosnapshot.v1.Sample
	(*SampleList)(nil), // 1: example.app.samplenosnapshot.v1.SampleList
	(*Create)(nil),     // 2: example.app.samplenosnapshot.v1.Create
	(*Update)(nil),     // 3: example.app.samplenosnapshot.v1.Update
	(*Created)(nil),    // 4: example.app.samplenosnapshot.v1.Created
	(*Updated)(nil),    // 5: example.app.samplenosnapshot.v1.Updated
}
var file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_depIdxs = []int32{
	0, // 0: example.app.samplenosnapshot.v1.SampleList.items:type_name -> example.app.samplenosnapshot.v1.Sample
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_init() }
func file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_init() {
	if File_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDesc), len(file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_goTypes,
		DependencyIndexes: file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_depIdxs,
		MessageInfos:      file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_msgTypes,
	}.Build()
	File_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto = out.File
	file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_goTypes = nil
	file_example_app_samplenosnapshot_v1_samplenosnapshot_v1_proto_depIdxs = nil
}
