// Code generated by protoc-gen-protosource. DO NOT EDIT.

package samplenoprefixv1

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	historyv1 "github.com/funinthecloud/protosource/history/v1"
	"github.com/funinthecloud/protosource/httpclient"
	"google.golang.org/protobuf/encoding/protojson"
)

const routePath = "example/app/samplenosnapshot/v1"

// HTTPClient is a typed HTTP client for the Sample aggregate.
type HTTPClient struct {
	c httpclient.Doer
}

// NewHTTPClient creates a new Sample HTTP client.
// Accepts httpclient.Doer for testability — use *httpclient.Client in
// production and a mock in tests.
func NewHTTPClient(c httpclient.Doer) *HTTPClient {
	return &HTTPClient{c: c}
}

// Create sends a Create command.
func (c *HTTPClient) Create(ctx context.Context, id string, body string) (*httpclient.ApplyResult, error) {
	cmd := &Create{
		Id:   id,
		Body: body,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Update sends a Update command.
func (c *HTTPClient) Update(ctx context.Context, id string, body string) (*httpclient.ApplyResult, error) {
	cmd := &Update{
		Id:   id,
		Body: body,
	}
	return c.c.Apply(ctx, routePath, cmd)
}

// Load retrieves the current state of a Sample aggregate.
func (c *HTTPClient) Load(ctx context.Context, id string) (*Sample, error) {
	agg := &Sample{}
	if err := c.c.Load(ctx, routePath, id, agg); err != nil {
		return nil, err
	}
	return agg, nil
}

// History retrieves the full event history for a Sample aggregate.
func (c *HTTPClient) History(ctx context.Context, id string) (*historyv1.History, error) {
	return c.c.History(ctx, routePath, id)
}

// Ensure strconv is used (suppresses unused import when no numeric GSI fields exist).
var _ = strconv.FormatInt

func unmarshalQueryResultsSample(raw []json.RawMessage, err error) ([]*Sample, error) {
	if err != nil {
		return nil, err
	}
	results := make([]*Sample, 0, len(raw))
	for _, item := range raw {
		agg := &Sample{}
		if err := protojson.Unmarshal(item, agg); err != nil {
			return nil, fmt.Errorf("unmarshal query result: %w", err)
		}
		results = append(results, agg)
	}
	return results, nil
}
