// Code generated by protoc-gen-protosource. DO NOT EDIT.

package samplenoprefixv1

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource/opaquedata"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// Repo is a package-specific interface for dependency injection.
// It embeds protosource.Repo so that *protosource.Repository satisfies it,
// while giving each aggregate package a distinct type for Wire.
type Repo interface {
	protosource.Repo
}

// Handler provides request handler functions for the Sample aggregate.
type Handler struct {
	repo   Repo
	client *SampleClient
}

// NewHandler creates a new Handler instance with the given repository and client.
func NewHandler(repo Repo, client *SampleClient) *Handler {
	return &Handler{repo: repo, client: client}
}

// RegisterRoutes registers all handler routes on the given router.
func (h *Handler) RegisterRoutes(router *protosource.Router) {

	router.Handle("POST", "example/app/samplenosnapshot/v1/create", h.HandleCreate)

	router.Handle("POST", "example/app/samplenosnapshot/v1/update", h.HandleUpdate)

	router.Handle("GET", "example/app/samplenosnapshot/v1/{id}", h.HandleGet)
	router.Handle("GET", "example/app/samplenosnapshot/v1/{id}/history", h.HandleHistory)

}

// HandleCreate processes a Create command.
func (h *Handler) HandleCreate(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return errorResponse(http.StatusUnauthorized, "CMD_NO_ACTOR", "no actor identity found", nil)
	}

	cmd := &Create{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return errorResponse(http.StatusBadRequest, "CMD_UNMARSHAL", "invalid request body", err)
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleUpdate processes a Update command.
func (h *Handler) HandleUpdate(ctx context.Context, request protosource.Request) protosource.Response {
	if request.Actor == "" {
		return errorResponse(http.StatusUnauthorized, "CMD_NO_ACTOR", "no actor identity found", nil)
	}

	cmd := &Update{}
	if err := unmarshalCommand(request, cmd); err != nil {
		return errorResponse(http.StatusBadRequest, "CMD_UNMARSHAL", "invalid request body", err)
	}

	// Override actor from auth context to prevent spoofing.
	cmd.Actor = request.Actor

	version, err := h.repo.Apply(ctx, cmd)
	if err != nil {
		return commandErrorResponse(err)
	}

	return jsonResponse(http.StatusOK, map[string]any{"id": cmd.GetId(), "version": version})
}

// HandleGet retrieves the current state of a Sample aggregate.
func (h *Handler) HandleGet(ctx context.Context, request protosource.Request) protosource.Response {
	id := extractID(request)
	if id == "" {
		return errorResponse(http.StatusBadRequest, "GET_NO_ID", "missing required parameter: id", nil)
	}

	aggregate, err := h.repo.Load(ctx, id)
	if err != nil {
		if errors.Is(err, protosource.ErrAggregateNotFound) {
			return errorResponse(http.StatusNotFound, "GET_NOT_FOUND", "aggregate not found", nil)
		}
		return errorResponse(http.StatusInternalServerError, "GET_LOAD", "failed to load aggregate", err)
	}

	body, contentType, err := marshalResponse(request, aggregate)
	if err != nil {
		return errorResponse(http.StatusInternalServerError, "GET_MARSHAL", "failed to serialize aggregate", err)
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": contentType},
	}
}

// HandleHistory retrieves the full event history for a Sample aggregate.
func (h *Handler) HandleHistory(ctx context.Context, request protosource.Request) protosource.Response {
	id := extractID(request)
	if id == "" {
		return errorResponse(http.StatusBadRequest, "HIST_NO_ID", "missing required parameter: id", nil)
	}

	history, err := h.repo.History(ctx, id)
	if err != nil {
		if errors.Is(err, protosource.ErrAggregateNotFound) {
			return errorResponse(http.StatusNotFound, "HIST_NOT_FOUND", "aggregate not found", nil)
		}
		return errorResponse(http.StatusInternalServerError, "HIST_LOAD", "failed to load history", err)
	}

	body, contentType, err := marshalResponse(request, history)
	if err != nil {
		return errorResponse(http.StatusInternalServerError, "HIST_MARSHAL", "failed to serialize history", err)
	}

	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": contentType},
	}
}

// ── Helpers ──

// acceptsProtobuf checks the Accept header: protobuf wins if present,
// then JSON if present, otherwise defaults to protobuf.
func acceptsProtobuf(request protosource.Request) bool {
	accept := request.Headers["Accept"]
	if accept == "" {
		accept = request.Headers["accept"]
	}
	if strings.Contains(accept, "application/protobuf") {
		return true
	}
	if strings.Contains(accept, "application/json") {
		return false
	}
	return true
}

// isProtobufContent checks the Content-Type header: protobuf wins if present,
// then JSON if present, otherwise defaults to protobuf.
func isProtobufContent(request protosource.Request) bool {
	ct := request.Headers["Content-Type"]
	if ct == "" {
		ct = request.Headers["content-type"]
	}
	if strings.Contains(ct, "application/protobuf") {
		return true
	}
	if strings.Contains(ct, "application/json") {
		return false
	}
	return true
}

// unmarshalCommand decodes the request body into a proto message, using
// Content-Type to select protobuf binary or JSON deserialization.
func unmarshalCommand(request protosource.Request, msg proto.Message) error {
	if isProtobufContent(request) {
		return proto.Unmarshal([]byte(request.Body), msg)
	}
	return protojson.Unmarshal([]byte(request.Body), msg)
}

// marshalResponse encodes a proto message for the response, using the Accept
// header to select protobuf binary or JSON serialization. Returns the
// serialized bytes and the appropriate Content-Type.
func marshalResponse(request protosource.Request, msg proto.Message) ([]byte, string, error) {
	if acceptsProtobuf(request) {
		b, err := proto.Marshal(msg)
		return b, "application/protobuf", err
	}
	b, err := protojson.Marshal(msg)
	return b, "application/json", err
}

// marshalQueryResults serializes a slice of proto messages as a JSON array.
func marshalQueryResults[T proto.Message](results []T) protosource.Response {
	items := make([]json.RawMessage, 0, len(results))
	for _, r := range results {
		b, err := protojson.Marshal(r)
		if err != nil {
			return errorResponse(http.StatusInternalServerError, "QUERY_MARSHAL", "failed to serialize result", err)
		}
		items = append(items, b)
	}
	body, err := json.Marshal(items)
	if err != nil {
		return errorResponse(http.StatusInternalServerError, "QUERY_MARSHAL", "failed to serialize results", err)
	}
	return protosource.Response{
		StatusCode: http.StatusOK,
		Body:       string(body),
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// extractID extracts the aggregate ID from path parameters or query string.
func extractID(request protosource.Request) string {
	if id, ok := request.PathParameters["id"]; ok && id != "" {
		return id
	}
	return request.QueryParameters["id"]
}

// parseSortOperator maps a query parameter value to an opaquedata.SortOperator.
func parseSortOperator(s string) (opaquedata.SortOperator, bool) {
	switch strings.ToLower(s) {
	case "eq":
		return opaquedata.Equal, true
	case "lt":
		return opaquedata.Lt, true
	case "le":
		return opaquedata.Le, true
	case "gt":
		return opaquedata.Gt, true
	case "ge":
		return opaquedata.Ge, true
	case "begins_with":
		return opaquedata.BeginsWith, true
	case "between":
		return opaquedata.Between, true
	default:
		return 0, false
	}
}

// errorResponse builds a JSON error response with a code for tracing.
// If cause is non-nil, its message is included in the detail field.
func errorResponse(statusCode int, code, message string, cause error) protosource.Response {
	body := map[string]string{"error": message, "code": code}
	if cause != nil {
		body["detail"] = cause.Error()
	}
	b, _ := json.Marshal(body)
	return protosource.Response{
		StatusCode: statusCode,
		Body:       string(b),
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// jsonResponse marshals a value as JSON and returns a protosource.Response.
func jsonResponse(statusCode int, v any) protosource.Response {
	b, err := json.Marshal(v)
	if err != nil {
		return errorResponse(http.StatusInternalServerError, "JSON_MARSHAL", "failed to serialize response", err)
	}
	return protosource.Response{
		StatusCode: statusCode,
		Body:       string(b),
		Headers:    map[string]string{"Content-Type": "application/json"},
	}
}

// commandErrorResponse maps protosource errors to appropriate HTTP responses.
func commandErrorResponse(err error) protosource.Response {
	switch {
	case errors.Is(err, protosource.ErrValidationFailed):
		return errorResponse(http.StatusBadRequest, "CMD_VALIDATION", err.Error(), nil)
	case errors.Is(err, protosource.ErrEmptyAggregateId):
		return errorResponse(http.StatusBadRequest, "CMD_EMPTY_ID", "aggregate id is required", nil)
	case errors.Is(err, protosource.ErrAlreadyCreated):
		return errorResponse(http.StatusConflict, "CMD_ALREADY_CREATED", "aggregate already exists", nil)
	case errors.Is(err, protosource.ErrNotCreatedYet):
		return errorResponse(http.StatusNotFound, "CMD_NOT_CREATED", "aggregate not found", nil)
	case errors.Is(err, protosource.ErrAggregateNotFound):
		return errorResponse(http.StatusNotFound, "CMD_NOT_FOUND", "aggregate not found", nil)
	case errors.Is(err, protosource.ErrUnauthorized):
		return errorResponse(http.StatusForbidden, "CMD_UNAUTHORIZED", "command not authorized", nil)
	default:
		return errorResponse(http.StatusInternalServerError, "CMD_INTERNAL", fmt.Sprintf("internal error: %s", err), nil)
	}
}

// ── Query parameter parsers ──

func parseQueryParamInt32(s string) int32 {
	v, _ := strconv.ParseInt(s, 10, 32)
	return int32(v)
}

func parseQueryParamInt64(s string) int64 {
	v, _ := strconv.ParseInt(s, 10, 64)
	return v
}
