
// Code generated by protoc-gen-protosource-ts. DO NOT EDIT.

import type { ProtosourceClient, CommandResponse, History } from "@protosource/client";
import { CreateSchema, UpdateSchema, SampleSchema, SampleListSchema } from "./sample_v1_pb.js";
import type { Create, Update, Sample, SampleList } from "./sample_v1_pb.js";

const routePath = "example/app/sample/v1";

export class SampleHTTPClient {
  private readonly client: ProtosourceClient;

  constructor(client: ProtosourceClient) {
    this.client = client;
  }

  async create(id: string, body: string): Promise<CommandResponse> {
    return this.client.apply(routePath, CreateSchema, { id, body });
  }

  async update(id: string, body: string): Promise<CommandResponse> {
    return this.client.apply(routePath, UpdateSchema, { id, body });
  }

  async load(id: string): Promise<Sample> {
    return this.client.load(routePath, id, SampleSchema);
  }

  async get(id: string): Promise<Sample> {
    return this.client.get(routePath, id, SampleSchema);
  }

  async history(id: string): Promise<History> {
    return this.client.history(routePath, id);
  }

  async queryByCreateBy(createBy: string): Promise<Sample[]> {
    const params: Record<string, string> = {
      "create_by": createBy,
    };
    const list = await this.client.query(routePath, "by-create-by", params, SampleListSchema);
    return list.items;
  }


  async queryByCreateByWithCreateAt(createBy: string, skOp: string, createAt: bigint): Promise<Sample[]> {
    if (skOp === "between") {
      throw new Error("use queryByCreateByBetweenCreateAt for between queries");
    }
    const params: Record<string, string> = {
      "create_by": createBy,
      "sk_op": skOp,
      "create_at": String(createAt),
    };
    const list = await this.client.query(routePath, "by-create-by", params, SampleListSchema);
    return list.items;
  }

  async queryByCreateByBetweenCreateAt(createBy: string, createAtFrom: bigint, createAtTo: bigint): Promise<Sample[]> {
    const params: Record<string, string> = {
      "create_by": createBy,
      "sk_op": "between",
      "create_at": String(createAtFrom),
      "create_at2": String(createAtTo),
    };
    const list = await this.client.query(routePath, "by-create-by", params, SampleListSchema);
    return list.items;
  }

}
