// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource/authz/allowall"
	orderv1 "github.com/funinthecloud/protosource/example/app/order/v1"
	samplev1 "github.com/funinthecloud/protosource/example/app/sample/v1"
	testv1 "github.com/funinthecloud/protosource/example/app/test/v1"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/cosmosdbstore"
)

// Injectors from wire.go:

// InitializeRouter wires all dependencies and returns a configured router.
func InitializeRouter(events cosmosdbstore.EventsContainerClient, aggregates cosmosdbstore.AggregatesContainerClient) (*protosource.Router, error) {
	store := cosmosdbstore.ProvideOpaqueStore(aggregates)
	cosmosDBStore, err := cosmosdbstore.ProvideStore(events, store)
	if err != nil {
		return nil, err
	}
	serializer := protobinaryserializer.NewSerializer()
	repository := testv1.ProvideRepository(cosmosDBStore, serializer)
	testClient := testv1.NewTestClient(store)
	authorizer := allowall.Provide()
	handler := testv1.NewHandler(repository, testClient, authorizer)
	orderv1Repository := orderv1.ProvideRepository(cosmosDBStore, serializer)
	orderClient := orderv1.NewOrderClient(store)
	orderv1Handler := orderv1.NewHandler(orderv1Repository, orderClient, authorizer)
	samplev1Repository := samplev1.ProvideRepository(cosmosDBStore, serializer)
	sampleClient := samplev1.NewSampleClient(store)
	samplev1Handler := samplev1.NewHandler(samplev1Repository, sampleClient, authorizer)
	router := provideRouter(handler, orderv1Handler, samplev1Handler)
	return router, nil
}

// wire.go:

func provideRouter(
	testHandler *testv1.Handler,
	orderHandler *orderv1.Handler,
	sampleHandler *samplev1.Handler,
) *protosource.Router {
	return protosource.NewRouter(testHandler, orderHandler, sampleHandler)
}
