name: Release
on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
          token: ${{ secrets.BUF_TOKEN }}

      - name: Push proto module
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf push --label ${GITHUB_REF_NAME}
