// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource/example/app/sample/v1"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/memorystore"
)

// Injectors from wire.go:

func InitializeRepository() *protosource.Repository {
	memoryStore := provideStore()
	serializer := protobinaryserializer.NewSerializer()
	repository := provideRepository(memoryStore, serializer)
	return repository
}

// wire.go:

func provideStore() *memorystore.MemoryStore {
	return memorystore.New(samplev1.SnapshotEveryNEvents)
}

func provideRepository(store *memorystore.MemoryStore, serializer *protobinaryserializer.Serializer) *protosource.Repository {
	return samplev1.NewRepository(protosource.WithStore(store), protosource.WithSerializer(serializer))
}
